#include "user32_internal.hpp"

namespace tradutorlinux::loader {

void register_user32_module() {
    static const ExportedFunction kUser32Exports[] = {
        {"MessageBoxA", 1, reinterpret_cast<std::uintptr_t>(&tl_MessageBoxA)},
        {"RegisterClassExA", 2, reinterpret_cast<std::uintptr_t>(&tl_RegisterClassExA)},
        {"CreateWindowExA", 3, reinterpret_cast<std::uintptr_t>(&tl_CreateWindowExA)},
        {"ShowWindow", 4, reinterpret_cast<std::uintptr_t>(&tl_ShowWindow)},
        {"UpdateWindow", 5, reinterpret_cast<std::uintptr_t>(&tl_UpdateWindow)},
        {"GetMessageA", 6, reinterpret_cast<std::uintptr_t>(&tl_GetMessageA)},
        {"TranslateMessage", 7, reinterpret_cast<std::uintptr_t>(&tl_TranslateMessage)},
        {"DispatchMessageA", 8, reinterpret_cast<std::uintptr_t>(&tl_DispatchMessageA)},
        {"DefWindowProcA", 9, reinterpret_cast<std::uintptr_t>(&tl_DefWindowProcA)},
        {"DestroyWindow", 10, reinterpret_cast<std::uintptr_t>(&tl_DestroyWindow)},
        {"PostQuitMessage", 11, reinterpret_cast<std::uintptr_t>(&tl_PostQuitMessage)},
        {"SetTimer", 12, reinterpret_cast<std::uintptr_t>(&tl_SetTimer)},
        {"KillTimer", 13, reinterpret_cast<std::uintptr_t>(&tl_KillTimer)},
        {"GetDC", 14, reinterpret_cast<std::uintptr_t>(&tl_GetDC)},
        {"ReleaseDC", 15, reinterpret_cast<std::uintptr_t>(&tl_ReleaseDC)},
        {"BeginPaint", 16, reinterpret_cast<std::uintptr_t>(&tl_BeginPaint)},
        {"EndPaint", 17, reinterpret_cast<std::uintptr_t>(&tl_EndPaint)},
        {"FillRect", 18, reinterpret_cast<std::uintptr_t>(&tl_FillRect)},
        {"RegisterClassA", 19, reinterpret_cast<std::uintptr_t>(&tl_RegisterClassA)},
        {"GetClientRect", 20, reinterpret_cast<std::uintptr_t>(&tl_GetClientRect)},
        {"GetCursorPos", 40, reinterpret_cast<std::uintptr_t>(&tl_GetCursorPos)},
        {"MoveWindow", 21, reinterpret_cast<std::uintptr_t>(&tl_MoveWindow)},
        {"SetWindowPos", 22, reinterpret_cast<std::uintptr_t>(&tl_SetWindowPos)},
        {"SetWindowTextA", 23, reinterpret_cast<std::uintptr_t>(&tl_SetWindowTextA)},
        {"GetWindowTextA", 24, reinterpret_cast<std::uintptr_t>(&tl_GetWindowTextA)},
        {"EnableWindow", 25, reinterpret_cast<std::uintptr_t>(&tl_EnableWindow)},
        {"SetFocus", 26, reinterpret_cast<std::uintptr_t>(&tl_SetFocus)},
        {"IsWindowVisible", 27, reinterpret_cast<std::uintptr_t>(&tl_IsWindowVisible)},
        {"InvalidateRect", 28, reinterpret_cast<std::uintptr_t>(&tl_InvalidateRect)},
        {"FindWindowA", 29, reinterpret_cast<std::uintptr_t>(&tl_FindWindowA)},
        {"LoadCursorA", 30, reinterpret_cast<std::uintptr_t>(&tl_LoadCursorA)},
        {"LoadIconA", 31, reinterpret_cast<std::uintptr_t>(&tl_LoadIconA)},
        {"SetClassLongPtrA", 32, reinterpret_cast<std::uintptr_t>(&tl_SetClassLongPtrA)},
        {"SetForegroundWindow", 33, reinterpret_cast<std::uintptr_t>(&tl_SetForegroundWindow)},
        {"SendMessageA", 34, reinterpret_cast<std::uintptr_t>(&tl_SendMessageA)},
        {"PostMessageA", 35, reinterpret_cast<std::uintptr_t>(&tl_PostMessageA)},
        {"CreatePopupMenu", 36, reinterpret_cast<std::uintptr_t>(&tl_CreatePopupMenu)},
        {"AppendMenuA", 37, reinterpret_cast<std::uintptr_t>(&tl_AppendMenuA)},
        {"DestroyMenu", 38, reinterpret_cast<std::uintptr_t>(&tl_DestroyMenu)},
        {"TrackPopupMenu", 39, reinterpret_cast<std::uintptr_t>(&tl_TrackPopupMenu)},
        {"GetSystemMetrics", 41, reinterpret_cast<std::uintptr_t>(&tl_GetSystemMetrics)},
        {"GetWindowLongPtrA", 42, reinterpret_cast<std::uintptr_t>(&tl_GetWindowLongPtrA)},
        {"GetWindowLongPtrW", 43, reinterpret_cast<std::uintptr_t>(&tl_GetWindowLongPtrW)},
        {"SetWindowLongPtrA", 44, reinterpret_cast<std::uintptr_t>(&tl_SetWindowLongPtrA)},
        {"SetWindowLongPtrW", 45, reinterpret_cast<std::uintptr_t>(&tl_SetWindowLongPtrW)},
        {"GetParent", 46, reinterpret_cast<std::uintptr_t>(&tl_GetParent)},
        {"SetParent", 47, reinterpret_cast<std::uintptr_t>(&tl_SetParent)},
        {"IsWindow", 48, reinterpret_cast<std::uintptr_t>(&tl_IsWindow)},
        {"MessageBoxW", 49, reinterpret_cast<std::uintptr_t>(&tl_MessageBoxW)},
        {"GetWindowDC", 50, reinterpret_cast<std::uintptr_t>(&tl_GetWindowDC)},
        {"SetCursor", 51, reinterpret_cast<std::uintptr_t>(&tl_SetCursor)},
        {"ShowCursor", 52, reinterpret_cast<std::uintptr_t>(&tl_ShowCursor)},
        {"SetCursorPos", 53, reinterpret_cast<std::uintptr_t>(&tl_SetCursorPos)},
        {"GetKeyState", 54, reinterpret_cast<std::uintptr_t>(&tl_GetKeyState)},
        {"GetAsyncKeyState", 55, reinterpret_cast<std::uintptr_t>(&tl_GetAsyncKeyState)},
        {"MsgWaitForMultipleObjects", 56, reinterpret_cast<std::uintptr_t>(&tl_MsgWaitForMultipleObjects)},
        {"MsgWaitForMultipleObjectsEx", 57, reinterpret_cast<std::uintptr_t>(&tl_MsgWaitForMultipleObjectsEx)},
        {"LoadStringA", 58, reinterpret_cast<std::uintptr_t>(&tl_LoadStringA)},
        {"LoadStringW", 59, reinterpret_cast<std::uintptr_t>(&tl_LoadStringW)},
        {"RegisterClassExW", 60, reinterpret_cast<std::uintptr_t>(&tl_RegisterClassExW)},
        {"RegisterClassW", 61, reinterpret_cast<std::uintptr_t>(&tl_RegisterClassW)},
        {"CreateWindowExW", 62, reinterpret_cast<std::uintptr_t>(&tl_CreateWindowExW)},
        {"GetMessageW", 63, reinterpret_cast<std::uintptr_t>(&tl_GetMessageW)},
        {"DispatchMessageW", 64, reinterpret_cast<std::uintptr_t>(&tl_DispatchMessageW)},
        {"DefWindowProcW", 65, reinterpret_cast<std::uintptr_t>(&tl_DefWindowProcW)},
        {"SetWindowTextW", 66, reinterpret_cast<std::uintptr_t>(&tl_SetWindowTextW)},
        {"GetWindowTextW", 67, reinterpret_cast<std::uintptr_t>(&tl_GetWindowTextW)},
        {"GetWindowTextLengthA", 68, reinterpret_cast<std::uintptr_t>(&tl_GetWindowTextLengthA)},
        {"GetWindowTextLengthW", 69, reinterpret_cast<std::uintptr_t>(&tl_GetWindowTextLengthW)},
        {"FindWindowW", 70, reinterpret_cast<std::uintptr_t>(&tl_FindWindowW)},
        {"LoadCursorW", 71, reinterpret_cast<std::uintptr_t>(&tl_LoadCursorW)},
        {"LoadIconW", 72, reinterpret_cast<std::uintptr_t>(&tl_LoadIconW)},
        {"SetClassLongPtrW", 73, reinterpret_cast<std::uintptr_t>(&tl_SetClassLongPtrW)},
        {"SendMessageW", 74, reinterpret_cast<std::uintptr_t>(&tl_SendMessageW)},
        {"PostMessageW", 75, reinterpret_cast<std::uintptr_t>(&tl_PostMessageW)},
        {"AppendMenuW", 76, reinterpret_cast<std::uintptr_t>(&tl_AppendMenuW)},
        {"DialogBoxParamW", 77, reinterpret_cast<std::uintptr_t>(&tl_DialogBoxParamW)},
        {"EndDialog", 78, reinterpret_cast<std::uintptr_t>(&tl_EndDialog)},
        {"GetDlgItem", 79, reinterpret_cast<std::uintptr_t>(&tl_GetDlgItem)},
        {"SetDlgItemTextW", 80, reinterpret_cast<std::uintptr_t>(&tl_SetDlgItemTextW)},
        {"SendDlgItemMessageW", 81, reinterpret_cast<std::uintptr_t>(&tl_SendDlgItemMessageW)},
        {"GetNextDlgTabItem", 82, reinterpret_cast<std::uintptr_t>(&tl_GetNextDlgTabItem)},
        {"IsDialogMessageW", 83, reinterpret_cast<std::uintptr_t>(&tl_IsDialogMessageW)},
        {"GetWindowRect", 84, reinterpret_cast<std::uintptr_t>(&tl_GetWindowRect)},
        {"GetWindowLongW", 85, reinterpret_cast<std::uintptr_t>(&tl_GetWindowLongW)},
        {"SetWindowLongW", 86, reinterpret_cast<std::uintptr_t>(&tl_SetWindowLongW)},
        {"CopyImage", 87, reinterpret_cast<std::uintptr_t>(&tl_CopyImage)},
        {"DestroyIcon", 88, reinterpret_cast<std::uintptr_t>(&tl_DestroyIcon)},
        {"GetDesktopWindow", 89, reinterpret_cast<std::uintptr_t>(&tl_GetDesktopWindow)},
        {"GetFocus", 90, reinterpret_cast<std::uintptr_t>(&tl_GetFocus)},
        {"SetCapture", 91, reinterpret_cast<std::uintptr_t>(&tl_SetCapture)},
        {"ReleaseCapture", 92, reinterpret_cast<std::uintptr_t>(&tl_ReleaseCapture)},
        {"GetCapture", 93, reinterpret_cast<std::uintptr_t>(&tl_GetCapture)},
        {"BringWindowToTop", 94, reinterpret_cast<std::uintptr_t>(&tl_BringWindowToTop)},
        {"GetWindow", 95, reinterpret_cast<std::uintptr_t>(&tl_GetWindow)},
        {"GetClassNameA", 96, reinterpret_cast<std::uintptr_t>(&tl_GetClassNameA)},
        {"GetClassNameW", 97, reinterpret_cast<std::uintptr_t>(&tl_GetClassNameW)},
        {"GetWindowThreadProcessId", 98,
         reinterpret_cast<std::uintptr_t>(&tl_GetWindowThreadProcessId)},
        {"CallWindowProcA", 99, reinterpret_cast<std::uintptr_t>(&tl_CallWindowProcA)},
        {"CallWindowProcW", 100, reinterpret_cast<std::uintptr_t>(&tl_CallWindowProcW)},
        {"PeekMessageA", 101, reinterpret_cast<std::uintptr_t>(&tl_PeekMessageA)},
        {"PeekMessageW", 102, reinterpret_cast<std::uintptr_t>(&tl_PeekMessageW)},
        {"RedrawWindow", 103, reinterpret_cast<std::uintptr_t>(&tl_RedrawWindow)},
        {"PtInRect", 104, reinterpret_cast<std::uintptr_t>(&tl_PtInRect)},
        {"CopyRect", 105, reinterpret_cast<std::uintptr_t>(&tl_CopyRect)},
        {"MapWindowPoints", 106, reinterpret_cast<std::uintptr_t>(&tl_MapWindowPoints)},
        {"MonitorFromWindow", 107, reinterpret_cast<std::uintptr_t>(&tl_MonitorFromWindow)},
        {"GetSysColor", 108, reinterpret_cast<std::uintptr_t>(&tl_GetSysColor)},
        {"CharUpperW", 109, reinterpret_cast<std::uintptr_t>(&tl_CharUpperW)},
        {"CharLowerW", 110, reinterpret_cast<std::uintptr_t>(&tl_CharLowerW)},
        {"DrawTextA", 111, reinterpret_cast<std::uintptr_t>(&tl_DrawTextA)},
        {"DrawTextW", 112, reinterpret_cast<std::uintptr_t>(&tl_DrawTextW)},
        {"SetUserObjectInformationW", 113,
         reinterpret_cast<std::uintptr_t>(&tl_SetUserObjectInformationW)},
        {"WaitForInputIdle", 114, reinterpret_cast<std::uintptr_t>(&tl_WaitForInputIdle)},
        {"FindWindowExW", 115, reinterpret_cast<std::uintptr_t>(&tl_FindWindowExW)},
        {"SetProcessDefaultLayout", 116,
         reinterpret_cast<std::uintptr_t>(&tl_SetProcessDefaultLayout)},
        {"OpenClipboard", 117, reinterpret_cast<std::uintptr_t>(&tl_OpenClipboard)},
        {"CloseClipboard", 118, reinterpret_cast<std::uintptr_t>(&tl_CloseClipboard)},
        {"SetClipboardData", 119, reinterpret_cast<std::uintptr_t>(&tl_SetClipboardData)},
        {"EmptyClipboard", 120, reinterpret_cast<std::uintptr_t>(&tl_EmptyClipboard)},
        {"MessageBoxExW", 121, reinterpret_cast<std::uintptr_t>(&tl_MessageBoxExW)},
        {"DrawIconEx", 122, reinterpret_cast<std::uintptr_t>(&tl_DrawIconEx)},
        {"LoadImageW", 123, reinterpret_cast<std::uintptr_t>(&tl_LoadImageW)},
        {"ClientToScreen", 124, reinterpret_cast<std::uintptr_t>(&tl_ClientToScreen)},
        {"GetMenu", 125, reinterpret_cast<std::uintptr_t>(&tl_GetMenu), ExportSupport::Limited},
        {"SetMenu", 126, reinterpret_cast<std::uintptr_t>(&tl_SetMenu), ExportSupport::Limited},
        {"GetSubMenu", 127, reinterpret_cast<std::uintptr_t>(&tl_GetSubMenu), ExportSupport::Limited},
        {"GetMenuItemCount", 128, reinterpret_cast<std::uintptr_t>(&tl_GetMenuItemCount), ExportSupport::Limited},
        {"GetMenuItemInfoW", 129, reinterpret_cast<std::uintptr_t>(&tl_GetMenuItemInfoW), ExportSupport::Limited},
        {"SetMenuItemInfoW", 130, reinterpret_cast<std::uintptr_t>(&tl_SetMenuItemInfoW), ExportSupport::Stub},
        {"InsertMenuItemW", 131, reinterpret_cast<std::uintptr_t>(&tl_InsertMenuItemW), ExportSupport::Limited},
        {"RemoveMenu", 132, reinterpret_cast<std::uintptr_t>(&tl_RemoveMenu), ExportSupport::Stub},
        {"EnableMenuItem", 133, reinterpret_cast<std::uintptr_t>(&tl_EnableMenuItem), ExportSupport::Limited},
        {"CheckMenuItem", 134, reinterpret_cast<std::uintptr_t>(&tl_CheckMenuItem), ExportSupport::Limited},
        {"CheckMenuRadioItem", 135, reinterpret_cast<std::uintptr_t>(&tl_CheckMenuRadioItem), ExportSupport::Limited},
        {"DrawMenuBar", 136, reinterpret_cast<std::uintptr_t>(&tl_DrawMenuBar), ExportSupport::Limited},
        {"TrackPopupMenuEx", 137, reinterpret_cast<std::uintptr_t>(&tl_TrackPopupMenuEx), ExportSupport::Stub},
        {"LoadMenuW", 138, reinterpret_cast<std::uintptr_t>(&tl_LoadMenuW), ExportSupport::Limited},
        {"CheckDlgButton", 139, reinterpret_cast<std::uintptr_t>(&tl_CheckDlgButton)},
        {"IsDlgButtonChecked", 140, reinterpret_cast<std::uintptr_t>(&tl_IsDlgButtonChecked)},
        {"CheckRadioButton", 141, reinterpret_cast<std::uintptr_t>(&tl_CheckRadioButton)},
        {"MapDialogRect", 142, reinterpret_cast<std::uintptr_t>(&tl_MapDialogRect)},
        {"GetDialogBaseUnits", 143, reinterpret_cast<std::uintptr_t>(&tl_GetDialogBaseUnits)},
        {"WindowFromPoint", 144, reinterpret_cast<std::uintptr_t>(&tl_WindowFromPoint)},
        {"ChildWindowFromPointEx", 145, reinterpret_cast<std::uintptr_t>(&tl_ChildWindowFromPointEx)},
        {"GetWindowPlacement", 146, reinterpret_cast<std::uintptr_t>(&tl_GetWindowPlacement)},
        {"SetWindowPlacement", 147, reinterpret_cast<std::uintptr_t>(&tl_SetWindowPlacement)},
        {"IsWindowEnabled", 148, reinterpret_cast<std::uintptr_t>(&tl_IsWindowEnabled)},
        {"IsZoomed", 149, reinterpret_cast<std::uintptr_t>(&tl_IsZoomed)},
        {"GetClassInfoW", 150, reinterpret_cast<std::uintptr_t>(&tl_GetClassInfoW)},
        {"GetMonitorInfoA", 151, reinterpret_cast<std::uintptr_t>(&tl_GetMonitorInfoA)},
        {"SystemParametersInfoW", 152, reinterpret_cast<std::uintptr_t>(&tl_SystemParametersInfoW)},
        {"LoadAcceleratorsW", 153, reinterpret_cast<std::uintptr_t>(&tl_LoadAcceleratorsW)},
        {"TranslateAcceleratorW", 154, reinterpret_cast<std::uintptr_t>(&tl_TranslateAcceleratorW)},
        {"LoadBitmapW", 155, reinterpret_cast<std::uintptr_t>(&tl_LoadBitmapW)},
        {"MapVirtualKeyW", 156, reinterpret_cast<std::uintptr_t>(&tl_MapVirtualKeyW)},
        {"RegisterClipboardFormatW", 157,
         reinterpret_cast<std::uintptr_t>(&tl_RegisterClipboardFormatW)},
        {"ScreenToClient", 158, reinterpret_cast<std::uintptr_t>(&tl_ScreenToClient)},
        {"CreateCaret", 159, reinterpret_cast<std::uintptr_t>(&tl_CreateCaret)},
        {"DestroyCaret", 160, reinterpret_cast<std::uintptr_t>(&tl_DestroyCaret)},
        {"SetCaretPos", 161, reinterpret_cast<std::uintptr_t>(&tl_SetCaretPos)},
        {"ShowCaret", 162, reinterpret_cast<std::uintptr_t>(&tl_ShowCaret)},
        {"HideCaret", 163, reinterpret_cast<std::uintptr_t>(&tl_HideCaret)},
        {"GetCaretPos", 164, reinterpret_cast<std::uintptr_t>(&tl_GetCaretPos)},
        {"SetScrollInfo", 165, reinterpret_cast<std::uintptr_t>(&tl_SetScrollInfo)},
        {"GetScrollInfo", 166, reinterpret_cast<std::uintptr_t>(&tl_GetScrollInfo)},
        {"ShowScrollBar", 167, reinterpret_cast<std::uintptr_t>(&tl_ShowScrollBar)},
        {"EnableScrollBar", 168, reinterpret_cast<std::uintptr_t>(&tl_EnableScrollBar)},
        {"SetScrollPos", 169, reinterpret_cast<std::uintptr_t>(&tl_SetScrollPos)},
        {"GetScrollPos", 170, reinterpret_cast<std::uintptr_t>(&tl_GetScrollPos)},
        {"SetScrollRange", 171, reinterpret_cast<std::uintptr_t>(&tl_SetScrollRange)},
        {"GetScrollRange", 172, reinterpret_cast<std::uintptr_t>(&tl_GetScrollRange)},
        {"SetCapture", 173, reinterpret_cast<std::uintptr_t>(&tl_SetCapture)},
        {"ReleaseCapture", 174, reinterpret_cast<std::uintptr_t>(&tl_ReleaseCapture)},
        {"GetCapture", 175, reinterpret_cast<std::uintptr_t>(&tl_GetCapture)},
        {"GetAsyncKeyState", 176, reinterpret_cast<std::uintptr_t>(&tl_GetAsyncKeyState)},
        {"GetKeyState", 177, reinterpret_cast<std::uintptr_t>(&tl_GetKeyState)},
        {"FlashWindow", 178, reinterpret_cast<std::uintptr_t>(&tl_FlashWindow)},
        {"FlashWindowEx", 179, reinterpret_cast<std::uintptr_t>(&tl_FlashWindowEx)},
        {"GetSysColor", 180, reinterpret_cast<std::uintptr_t>(&tl_GetSysColor)},
        {"SetSysColors", 181, reinterpret_cast<std::uintptr_t>(&tl_SetSysColors)},
        {"MessageBeep", 182, reinterpret_cast<std::uintptr_t>(&tl_MessageBeep)},
        {"TrackPopupMenu", 183, reinterpret_cast<std::uintptr_t>(&tl_TrackPopupMenu)},
        {"GetClipboardData", 184, reinterpret_cast<std::uintptr_t>(&tl_GetClipboardData)},
        {"IsClipboardFormatAvailable", 185, reinterpret_cast<std::uintptr_t>(&tl_IsClipboardFormatAvailable)},
        {"RegisterClipboardFormatA", 186, reinterpret_cast<std::uintptr_t>(&tl_RegisterClipboardFormatA)},
        {"CountClipboardFormats", 187, reinterpret_cast<std::uintptr_t>(&tl_CountClipboardFormats)},
        {"EnumClipboardFormats", 188, reinterpret_cast<std::uintptr_t>(&tl_EnumClipboardFormats)},
        {"GetDpiForWindow", 189, reinterpret_cast<std::uintptr_t>(&tl_GetDpiForWindow)},
        {"GetDpiForSystem", 190, reinterpret_cast<std::uintptr_t>(&tl_GetDpiForSystem)},
        {"SetProcessDpiAwarenessContext", 191, reinterpret_cast<std::uintptr_t>(&tl_SetProcessDpiAwarenessContext)},
        {"SetProcessDPIAware", 192, reinterpret_cast<std::uintptr_t>(&tl_SetProcessDPIAware)},
        {"GetSystemMetricsForDpi", 193, reinterpret_cast<std::uintptr_t>(&tl_GetSystemMetricsForDpi)},
        {"AdjustWindowRectExForDpi", 194, reinterpret_cast<std::uintptr_t>(&tl_AdjustWindowRectExForDpi)},
        {"CreateIconIndirect", 195, reinterpret_cast<std::uintptr_t>(&tl_CreateIconIndirect)},
        {"GetIconInfo", 196, reinterpret_cast<std::uintptr_t>(&tl_GetIconInfo)},
        {"GetIconInfoExW", 197, reinterpret_cast<std::uintptr_t>(&tl_GetIconInfoExW)},
        {"DrawIcon", 198, reinterpret_cast<std::uintptr_t>(&tl_DrawIcon)},
        {"CopyIcon", 199, reinterpret_cast<std::uintptr_t>(&tl_CopyIcon)},
        {"SetWindowRgn", 200, reinterpret_cast<std::uintptr_t>(&tl_SetWindowRgn)},
        {"GetWindowRgn", 201, reinterpret_cast<std::uintptr_t>(&tl_GetWindowRgn)},
        {"GetWindowRgnBox", 202, reinterpret_cast<std::uintptr_t>(&tl_GetWindowRgnBox)},
        {"DrawEdge", 203, reinterpret_cast<std::uintptr_t>(&tl_DrawEdge)},
        {"DrawFrameControl", 204, reinterpret_cast<std::uintptr_t>(&tl_DrawFrameControl)},
        {"DrawFocusRect", 205, reinterpret_cast<std::uintptr_t>(&tl_DrawFocusRect)},
        {"FillRect", 206, reinterpret_cast<std::uintptr_t>(&tl_FillRect)},
        {"FrameRect", 207, reinterpret_cast<std::uintptr_t>(&tl_FrameRect)},
        {"InvertRect", 208, reinterpret_cast<std::uintptr_t>(&tl_InvertRect)},
        {"GetUpdateRect", 209, reinterpret_cast<std::uintptr_t>(&tl_GetUpdateRect)},
        {"GetUpdateRgn", 210, reinterpret_cast<std::uintptr_t>(&tl_GetUpdateRgn)},
        {"InvalidateRgn", 211, reinterpret_cast<std::uintptr_t>(&tl_InvalidateRgn)},
        {"ValidateRgn", 212, reinterpret_cast<std::uintptr_t>(&tl_ValidateRgn)},
        {"ScrollWindow", 213, reinterpret_cast<std::uintptr_t>(&tl_ScrollWindow)},
        {"ScrollWindowEx", 214, reinterpret_cast<std::uintptr_t>(&tl_ScrollWindowEx)},
        {"RegisterHotKey", 215, reinterpret_cast<std::uintptr_t>(&tl_RegisterHotKey)},
        {"UnregisterHotKey", 216, reinterpret_cast<std::uintptr_t>(&tl_UnregisterHotKey)},
        {"GetProcessWindowStation", 217, reinterpret_cast<std::uintptr_t>(&tl_GetProcessWindowStation)},
        {"GetUserObjectInformationW", 218, reinterpret_cast<std::uintptr_t>(&tl_GetUserObjectInformationW)},
        {"GetShellWindow", 219, reinterpret_cast<std::uintptr_t>(&tl_GetShellWindow)},
        {"EnumDisplayDevicesA", 220, reinterpret_cast<std::uintptr_t>(&tl_EnumDisplayDevicesA)},
        {"CreateDialogParamA", 221, reinterpret_cast<std::uintptr_t>(&tl_CreateDialogParamA)},
        {"CreateMenu", 222, reinterpret_cast<std::uintptr_t>(&tl_CreateMenu)},
        {"DefDlgProcA", 223, reinterpret_cast<std::uintptr_t>(&tl_DefDlgProcA)},
        {"DeleteMenu", 224, reinterpret_cast<std::uintptr_t>(&tl_DeleteMenu)},
        {"DialogBoxParamA", 225, reinterpret_cast<std::uintptr_t>(&tl_DialogBoxParamA), ExportSupport::Limited},
        {"GetCaretBlinkTime", 226, reinterpret_cast<std::uintptr_t>(&tl_GetCaretBlinkTime)},
        {"GetClipboardOwner", 227, reinterpret_cast<std::uintptr_t>(&tl_GetClipboardOwner)},
        {"GetDoubleClickTime", 228, reinterpret_cast<std::uintptr_t>(&tl_GetDoubleClickTime)},
        {"GetForegroundWindow", 229, reinterpret_cast<std::uintptr_t>(&tl_GetForegroundWindow)},
        {"GetKeyboardLayout", 230, reinterpret_cast<std::uintptr_t>(&tl_GetKeyboardLayout)},
        {"GetKeyboardState", 231, reinterpret_cast<std::uintptr_t>(&tl_GetKeyboardState)},
        {"GetMessageTime", 232, reinterpret_cast<std::uintptr_t>(&tl_GetMessageTime)},
        {"GetQueueStatus", 233, reinterpret_cast<std::uintptr_t>(&tl_GetQueueStatus)},
        {"GetSysColorBrush", 234, reinterpret_cast<std::uintptr_t>(&tl_GetSysColorBrush)},
        {"GetSystemMenu", 235, reinterpret_cast<std::uintptr_t>(&tl_GetSystemMenu)},
        {"InsertMenuA", 236, reinterpret_cast<std::uintptr_t>(&tl_InsertMenuA)},
        {"IsDialogMessageA", 237, reinterpret_cast<std::uintptr_t>(&tl_IsDialogMessageA)},
        {"IsIconic", 238, reinterpret_cast<std::uintptr_t>(&tl_IsIconic)},
        {"LoadImageA", 239, reinterpret_cast<std::uintptr_t>(&tl_LoadImageA)},
        {"MessageBoxIndirectW", 240, reinterpret_cast<std::uintptr_t>(&tl_MessageBoxIndirectW)},
        {"OffsetRect", 241, reinterpret_cast<std::uintptr_t>(&tl_OffsetRect)},
        {"RegisterWindowMessageA", 242, reinterpret_cast<std::uintptr_t>(&tl_RegisterWindowMessageA)},
        {"SendDlgItemMessageA", 243, reinterpret_cast<std::uintptr_t>(&tl_SendDlgItemMessageA)},
        {"SetActiveWindow", 244, reinterpret_cast<std::uintptr_t>(&tl_SetActiveWindow)},
        {"SetDlgItemTextA", 245, reinterpret_cast<std::uintptr_t>(&tl_SetDlgItemTextA)},
        {"SetKeyboardState", 246, reinterpret_cast<std::uintptr_t>(&tl_SetKeyboardState)},
        {"SystemParametersInfoA", 247, reinterpret_cast<std::uintptr_t>(&tl_SystemParametersInfoA)},
        {"ToAsciiEx", 248, reinterpret_cast<std::uintptr_t>(&tl_ToAsciiEx)},
        {"RegisterWindowMessageW", 249, reinterpret_cast<std::uintptr_t>(&tl_RegisterWindowMessageW)},
        {"RemovePropW", 250, reinterpret_cast<std::uintptr_t>(&tl_RemovePropW)},
        {"GetPropW", 251, reinterpret_cast<std::uintptr_t>(&tl_GetPropW)},
        {"SetPropW", 252, reinterpret_cast<std::uintptr_t>(&tl_SetPropW)},
        {"ValidateRect", 253, reinterpret_cast<std::uintptr_t>(&tl_ValidateRect)},
        {"DestroyCursor", 254, reinterpret_cast<std::uintptr_t>(&tl_DestroyCursor)},
        {"NotifyWinEvent", 255, reinterpret_cast<std::uintptr_t>(&tl_NotifyWinEvent)},
        {"MonitorFromPoint", 256, reinterpret_cast<std::uintptr_t>(&tl_MonitorFromPoint)},
        {"MonitorFromRect", 257, reinterpret_cast<std::uintptr_t>(&tl_MonitorFromRect)},
        {"GetMonitorInfoW", 258, reinterpret_cast<std::uintptr_t>(&tl_GetMonitorInfoW)},
        {"AdjustWindowRectEx", 259, reinterpret_cast<std::uintptr_t>(&tl_AdjustWindowRectEx)},
        {"GetDlgItemTextA", 260, reinterpret_cast<std::uintptr_t>(&tl_GetDlgItemTextA)},
        {"GetDlgItemTextW", 261, reinterpret_cast<std::uintptr_t>(&tl_GetDlgItemTextW)},
        {"BeginDeferWindowPos", 262, reinterpret_cast<std::uintptr_t>(&tl_BeginDeferWindowPos)},
        {"DeferWindowPos", 263, reinterpret_cast<std::uintptr_t>(&tl_DeferWindowPos)},
        {"EndDeferWindowPos", 264, reinterpret_cast<std::uintptr_t>(&tl_EndDeferWindowPos)},
        {"UnregisterClassW", 265, reinterpret_cast<std::uintptr_t>(&tl_UnregisterClassW)},
        {"GetActiveWindow", 266, reinterpret_cast<std::uintptr_t>(&tl_GetActiveWindow)},
        {"CallNextHookEx", 267, reinterpret_cast<std::uintptr_t>(&tl_CallNextHookEx)},
        {"UnhookWindowsHookEx", 268, reinterpret_cast<std::uintptr_t>(&tl_UnhookWindowsHookEx)},
        {"SetWindowsHookExW", 269, reinterpret_cast<std::uintptr_t>(&tl_SetWindowsHookExW)},
        {"GetMenuState", 270, reinterpret_cast<std::uintptr_t>(&tl_GetMenuState)},
        {"InsertMenuW", 271, reinterpret_cast<std::uintptr_t>(&tl_InsertMenuW)},
        {"GetDlgItemInt", 272, reinterpret_cast<std::uintptr_t>(&tl_GetDlgItemInt)},
        {"SetDlgItemInt", 273, reinterpret_cast<std::uintptr_t>(&tl_SetDlgItemInt)},
        {"CreateDialogParamW", 274, reinterpret_cast<std::uintptr_t>(&tl_CreateDialogParamW)},
        {"CreateDialogIndirectParamW", 275, reinterpret_cast<std::uintptr_t>(&tl_CreateDialogIndirectParamW)},
        {"DialogBoxIndirectParamW", 276, reinterpret_cast<std::uintptr_t>(&tl_DialogBoxIndirectParamW)},
        {"SetClipboardViewer", 277, reinterpret_cast<std::uintptr_t>(&tl_SetClipboardViewer)},
        {"ChangeClipboardChain", 278, reinterpret_cast<std::uintptr_t>(&tl_ChangeClipboardChain)},
        {"DrawTextExW", 279, reinterpret_cast<std::uintptr_t>(&tl_DrawTextExW)},
        {"ToAscii", 280, reinterpret_cast<std::uintptr_t>(&tl_ToAscii)},
        {"CreateAcceleratorTableW", 281, reinterpret_cast<std::uintptr_t>(&tl_CreateAcceleratorTableW)},
        {"DestroyAcceleratorTable", 282, reinterpret_cast<std::uintptr_t>(&tl_DestroyAcceleratorTable)},
        {"IsCharLowerW", 283, reinterpret_cast<std::uintptr_t>(&tl_IsCharLowerW)},
        {"IsCharAlphaNumericW", 284, reinterpret_cast<std::uintptr_t>(&tl_IsCharAlphaNumericW)},
        {"IsCharAlphaW", 285, reinterpret_cast<std::uintptr_t>(&tl_IsCharAlphaW)},
        {"ModifyMenuW", 286, reinterpret_cast<std::uintptr_t>(&tl_ModifyMenuW)},
        {"InflateRect", 287, reinterpret_cast<std::uintptr_t>(&tl_InflateRect)},
        {"IntersectRect", 288, reinterpret_cast<std::uintptr_t>(&tl_IntersectRect)},
        {"SetRectEmpty", 289, reinterpret_cast<std::uintptr_t>(&tl_SetRectEmpty)},
        {"EnumChildWindows", 290, reinterpret_cast<std::uintptr_t>(&tl_EnumChildWindows)},
        {"EnumThreadWindows", 291, reinterpret_cast<std::uintptr_t>(&tl_EnumThreadWindows)},
        {"GetMenuBarInfo", 292, reinterpret_cast<std::uintptr_t>(&tl_GetMenuBarInfo)},
        {"TrackMouseEvent", 293, reinterpret_cast<std::uintptr_t>(&tl_TrackMouseEvent)},
        {"GetComboBoxInfo", 294, reinterpret_cast<std::uintptr_t>(&tl_GetComboBoxInfo)},
        {"ChildWindowFromPoint", 295, reinterpret_cast<std::uintptr_t>(&tl_ChildWindowFromPoint)},
        {"GetDlgCtrlID", 296, reinterpret_cast<std::uintptr_t>(&tl_GetDlgCtrlID)},
        {"wsprintfW", 297, reinterpret_cast<std::uintptr_t>(&tl_wsprintfW)},
        {"GetAncestor", 298, reinterpret_cast<std::uintptr_t>(&tl_GetAncestor)},
        {"GetMenuItemID", 299, reinterpret_cast<std::uintptr_t>(&tl_GetMenuItemID)},
        {"SetLayeredWindowAttributes", 300, reinterpret_cast<std::uintptr_t>(&tl_SetLayeredWindowAttributes)},
        {"GetLastActivePopup", 301, reinterpret_cast<std::uintptr_t>(&tl_GetLastActivePopup)},
        {"GetMenuStringW", 302, reinterpret_cast<std::uintptr_t>(&tl_GetMenuStringW)},
        {"LockWindowUpdate", 303, reinterpret_cast<std::uintptr_t>(&tl_LockWindowUpdate)},
        {"mouse_event", 304, reinterpret_cast<std::uintptr_t>(&tl_mouse_event)},
        {"SetMenuItemBitmaps", 305, reinterpret_cast<std::uintptr_t>(&tl_SetMenuItemBitmaps)},
        {"GetDCEx", 306, reinterpret_cast<std::uintptr_t>(&tl_GetDCEx)},
        {"IsChild", 307, reinterpret_cast<std::uintptr_t>(&tl_IsChild)},
        {"CharPrevExA", 308, reinterpret_cast<std::uintptr_t>(&tl_CharPrevExA)},
        {"SetWindowsHookExA", 309, reinterpret_cast<std::uintptr_t>(&tl_SetWindowsHookExA)},
        {"SendMessageTimeoutA", 310, reinterpret_cast<std::uintptr_t>(&tl_SendMessageTimeoutA)},
        {"WindowFromDC", 311, reinterpret_cast<std::uintptr_t>(&tl_WindowFromDC)},
        {"FindWindowExA", 312, reinterpret_cast<std::uintptr_t>(&tl_FindWindowExA)},
        {"EnumDisplaySettingsA", 313, reinterpret_cast<std::uintptr_t>(&tl_EnumDisplaySettingsA)},
        {"IsRectEmpty", 314, reinterpret_cast<std::uintptr_t>(&tl_IsRectEmpty)},
        {"SubtractRect", 315, reinterpret_cast<std::uintptr_t>(&tl_SubtractRect)},
    };
    static const InternalModule kUser32Module{"USER32.dll", kUser32Exports};
    register_module(kUser32Module);
}

}  // namespace tradutorlinux::loader
