#ifndef TRADUTORLINUX_FFI_RUST_MSIX_PARSER_H
#define TRADUTORLINUX_FFI_RUST_MSIX_PARSER_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint32_t tl_msix_status_t;
typedef uint32_t tl_msix_error_code_t;
typedef uint32_t tl_msix_error_phase_t;

#define TL_MSIX_STATUS_SUCCESS UINT32_C(0)
#define TL_MSIX_STATUS_TRUNCATED UINT32_C(1)
#define TL_MSIX_STATUS_MALFORMED UINT32_C(2)
#define TL_MSIX_STATUS_UNSUPPORTED_FORMAT UINT32_C(3)
#define TL_MSIX_STATUS_UNSUPPORTED_MECHANISM UINT32_C(4)
#define TL_MSIX_STATUS_INVALID_ARGUMENT UINT32_C(5)
#define TL_MSIX_STATUS_BUFFER_TOO_SMALL UINT32_C(6)
#define TL_MSIX_STATUS_INPUT_TOO_LARGE UINT32_C(7)
#define TL_MSIX_STATUS_OUTPUT_TOO_LARGE UINT32_C(8)
#define TL_MSIX_STATUS_INTERNAL UINT32_C(9)

#define TL_MSIX_ERROR_NONE UINT32_C(0)
#define TL_MSIX_ERROR_INVALID_ARGUMENT UINT32_C(1)
#define TL_MSIX_ERROR_BUFFER_TOO_SMALL UINT32_C(2)
#define TL_MSIX_ERROR_INPUT_TOO_LARGE UINT32_C(3)
#define TL_MSIX_ERROR_OUTPUT_TOO_LARGE UINT32_C(4)
#define TL_MSIX_ERROR_INTERNAL UINT32_C(5)
#define TL_MSIX_ERROR_ZIP_EOCD UINT32_C(16)
#define TL_MSIX_ERROR_ZIP_CENTRAL_DIRECTORY UINT32_C(17)
#define TL_MSIX_ERROR_ZIP_LOCAL_HEADER UINT32_C(18)
#define TL_MSIX_ERROR_ZIP_ENTRY UINT32_C(19)
#define TL_MSIX_ERROR_ZIP_PATH UINT32_C(20)
#define TL_MSIX_ERROR_ZIP_LINK UINT32_C(21)
#define TL_MSIX_ERROR_ZIP_COMPRESSION UINT32_C(22)
#define TL_MSIX_ERROR_ZIP_CRC UINT32_C(23)
#define TL_MSIX_ERROR_XML_SYNTAX UINT32_C(24)
#define TL_MSIX_ERROR_XML_ENTITY UINT32_C(25)
#define TL_MSIX_ERROR_XML_LIMIT UINT32_C(26)
#define TL_MSIX_ERROR_MANIFEST UINT32_C(27)
#define TL_MSIX_ERROR_WIRE_FORMAT UINT32_C(28)

#define TL_MSIX_ERROR_PHASE_NONE UINT32_C(0)
#define TL_MSIX_ERROR_PHASE_INPUT UINT32_C(1)
#define TL_MSIX_ERROR_PHASE_ZIP_EOCD UINT32_C(2)
#define TL_MSIX_ERROR_PHASE_ZIP_CENTRAL_DIRECTORY UINT32_C(3)
#define TL_MSIX_ERROR_PHASE_ZIP_ENTRY UINT32_C(4)
#define TL_MSIX_ERROR_PHASE_ZIP_DECOMPRESS UINT32_C(5)
#define TL_MSIX_ERROR_PHASE_XML UINT32_C(6)
#define TL_MSIX_ERROR_PHASE_MANIFEST UINT32_C(7)
#define TL_MSIX_ERROR_PHASE_SERIALIZE UINT32_C(8)
#define TL_MSIX_ERROR_PHASE_WIRE UINT32_C(9)

#define TL_MSIX_ERROR_OFFSET_UNKNOWN UINT64_MAX

typedef struct tl_msix_error_v1 {
    uint32_t code;
    uint32_t phase;
    uint64_t input_offset;
    uint64_t detail_value;
} tl_msix_error_v1;

#define TL_MSIX_WIRE_MAGIC_0 UINT8_C(0x54) /* T */
#define TL_MSIX_WIRE_MAGIC_1 UINT8_C(0x4C) /* L */
#define TL_MSIX_WIRE_MAGIC_2 UINT8_C(0x4D) /* M */
#define TL_MSIX_WIRE_MAGIC_3 UINT8_C(0x53) /* S */
#define TL_MSIX_WIRE_MAJOR UINT16_C(1)
#define TL_MSIX_WIRE_MINOR UINT16_C(0)

#define TL_MSIX_WIRE_HEADER_SIZE UINT32_C(128)
#define TL_MSIX_WIRE_TABLE_DESCRIPTOR_SIZE UINT32_C(24)
#define TL_MSIX_WIRE_TABLE_DESCRIPTOR_OFFSET UINT32_C(32)
#define TL_MSIX_WIRE_TABLE_COUNT UINT32_C(4)
#define TL_MSIX_WIRE_TABLE_FLAG_VARIABLE_RECORDS UINT32_C(1)

#define TL_MSIX_WIRE_HEADER_MAGIC_OFFSET UINT32_C(0)
#define TL_MSIX_WIRE_HEADER_MAJOR_OFFSET UINT32_C(4)
#define TL_MSIX_WIRE_HEADER_MINOR_OFFSET UINT32_C(6)
#define TL_MSIX_WIRE_HEADER_SIZE_OFFSET UINT32_C(8)
#define TL_MSIX_WIRE_HEADER_TOTAL_SIZE_OFFSET UINT32_C(12)
#define TL_MSIX_WIRE_HEADER_TABLE_COUNT_OFFSET UINT32_C(20)
#define TL_MSIX_WIRE_HEADER_FLAGS_OFFSET UINT32_C(24)
#define TL_MSIX_WIRE_HEADER_RESERVED_OFFSET UINT32_C(28)

#define TL_MSIX_WIRE_DESCRIPTOR_OFFSET_FIELD UINT32_C(0)
#define TL_MSIX_WIRE_DESCRIPTOR_COUNT_FIELD UINT32_C(8)
#define TL_MSIX_WIRE_DESCRIPTOR_STRIDE_FIELD UINT32_C(16)
#define TL_MSIX_WIRE_DESCRIPTOR_FLAGS_FIELD UINT32_C(20)

#define TL_MSIX_WIRE_TABLE_INFO UINT32_C(0)
#define TL_MSIX_WIRE_TABLE_APPLICATIONS UINT32_C(1)
#define TL_MSIX_WIRE_TABLE_STRINGS UINT32_C(2)
#define TL_MSIX_WIRE_TABLE_RESERVED UINT32_C(3)

#define TL_MSIX_WIRE_INFO_STRIDE UINT32_C(64)
#define TL_MSIX_WIRE_APPLICATION_STRIDE UINT32_C(64)
#define TL_MSIX_WIRE_STRING_REF_SIZE UINT32_C(16)
#define TL_MSIX_WIRE_STRING_RECORD_HEADER_SIZE UINT32_C(8)

#define TL_MSIX_WIRE_INFO_PACKAGE_NAME_OFFSET UINT32_C(0)
#define TL_MSIX_WIRE_INFO_PUBLISHER_OFFSET UINT32_C(16)
#define TL_MSIX_WIRE_INFO_VERSION_OFFSET UINT32_C(32)
#define TL_MSIX_WIRE_INFO_MAIN_EXECUTABLE_OFFSET UINT32_C(48)

#define TL_MSIX_WIRE_APPLICATION_ID_OFFSET UINT32_C(0)
#define TL_MSIX_WIRE_APPLICATION_EXECUTABLE_OFFSET UINT32_C(16)
#define TL_MSIX_WIRE_APPLICATION_DISPLAY_NAME_OFFSET UINT32_C(32)
#define TL_MSIX_WIRE_APPLICATION_ENTRY_POINT_OFFSET UINT32_C(48)

#define TL_MSIX_LIMIT_MAX_PACKAGE_BYTES UINT64_C(2147483648)
#define TL_MSIX_LIMIT_MAX_MANIFEST_BYTES UINT64_C(16777216)
#define TL_MSIX_LIMIT_MAX_MANIFEST_COMPRESSED_BYTES UINT64_C(67108864)
#define TL_MSIX_LIMIT_MAX_ZIP_ENTRIES UINT64_C(10000)
#define TL_MSIX_LIMIT_MAX_ZIP_FILENAME_BYTES UINT64_C(4096)
#define TL_MSIX_LIMIT_MAX_ENTRY_UNCOMPRESSED_BYTES UINT64_C(536870912)
#define TL_MSIX_LIMIT_MAX_PACKAGE_UNCOMPRESSED_BYTES UINT64_C(536870912)
#define TL_MSIX_LIMIT_MAX_XML_DEPTH UINT64_C(128)
#define TL_MSIX_LIMIT_MAX_XML_ATTRIBUTES UINT64_C(256)
#define TL_MSIX_LIMIT_MAX_STRINGS UINT64_C(50000)
#define TL_MSIX_LIMIT_MAX_SERIALIZED_BYTES UINT64_C(67108864)

/*
 * Both functions are stateless. The caller owns input, output and the error
 * message buffer. Rust never retains or returns a pointer into its memory.
 * output_required and error_required are mandatory and include no hidden NUL
 * or record bytes beyond the documented sizes.
 */
tl_msix_status_t tl_msix_parse_v1_size(
    const uint8_t* input,
    uint64_t input_length,
    uint64_t* output_required,
    tl_msix_error_v1* error,
    char* error_message,
    uint64_t error_capacity,
    uint64_t* error_required);

tl_msix_status_t tl_msix_parse_v1_fill(
    const uint8_t* input,
    uint64_t input_length,
    uint8_t* output,
    uint64_t output_capacity,
    uint64_t* output_required,
    tl_msix_error_v1* error,
    char* error_message,
    uint64_t error_capacity,
    uint64_t* error_required);

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif  /* TRADUTORLINUX_FFI_RUST_MSIX_PARSER_H */
