#ifndef TRADUTORLINUX_FFI_RUST_APP_CATALOG_PARSER_H
#define TRADUTORLINUX_FFI_RUST_APP_CATALOG_PARSER_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint32_t tl_app_catalog_status_t;
typedef uint32_t tl_app_catalog_error_code_t;
typedef uint32_t tl_app_catalog_error_phase_t;

#define TL_APP_CATALOG_STATUS_SUCCESS UINT32_C(0)
#define TL_APP_CATALOG_STATUS_MALFORMED UINT32_C(1)
#define TL_APP_CATALOG_STATUS_UNSUPPORTED_FORMAT UINT32_C(2)
#define TL_APP_CATALOG_STATUS_INVALID_ARGUMENT UINT32_C(3)
#define TL_APP_CATALOG_STATUS_BUFFER_TOO_SMALL UINT32_C(4)
#define TL_APP_CATALOG_STATUS_INPUT_TOO_LARGE UINT32_C(5)
#define TL_APP_CATALOG_STATUS_OUTPUT_TOO_LARGE UINT32_C(6)
#define TL_APP_CATALOG_STATUS_INTERNAL UINT32_C(7)

#define TL_APP_CATALOG_ERROR_NONE UINT32_C(0)
#define TL_APP_CATALOG_ERROR_INVALID_ARGUMENT UINT32_C(1)
#define TL_APP_CATALOG_ERROR_BUFFER_TOO_SMALL UINT32_C(2)
#define TL_APP_CATALOG_ERROR_INPUT_TOO_LARGE UINT32_C(3)
#define TL_APP_CATALOG_ERROR_OUTPUT_TOO_LARGE UINT32_C(4)
#define TL_APP_CATALOG_ERROR_INTERNAL UINT32_C(5)
#define TL_APP_CATALOG_ERROR_JSON_SYNTAX UINT32_C(16)
#define TL_APP_CATALOG_ERROR_JSON_FIELD UINT32_C(17)
#define TL_APP_CATALOG_ERROR_SCHEMA UINT32_C(18)
#define TL_APP_CATALOG_ERROR_VALUE UINT32_C(19)
#define TL_APP_CATALOG_ERROR_LIMIT UINT32_C(20)
#define TL_APP_CATALOG_ERROR_WIRE_FORMAT UINT32_C(21)

#define TL_APP_CATALOG_ERROR_PHASE_NONE UINT32_C(0)
#define TL_APP_CATALOG_ERROR_PHASE_INPUT UINT32_C(1)
#define TL_APP_CATALOG_ERROR_PHASE_JSON UINT32_C(2)
#define TL_APP_CATALOG_ERROR_PHASE_SCHEMA UINT32_C(3)
#define TL_APP_CATALOG_ERROR_PHASE_SERIALIZE UINT32_C(4)
#define TL_APP_CATALOG_ERROR_PHASE_WIRE UINT32_C(5)

#define TL_APP_CATALOG_ERROR_OFFSET_UNKNOWN UINT64_MAX

typedef struct tl_app_catalog_error_v1 {
    uint32_t code;
    uint32_t phase;
    uint64_t input_offset;
    uint64_t detail_value;
} tl_app_catalog_error_v1;

#define TL_APP_CATALOG_WIRE_MAGIC_0 UINT8_C(0x54) /* T */
#define TL_APP_CATALOG_WIRE_MAGIC_1 UINT8_C(0x4C) /* L */
#define TL_APP_CATALOG_WIRE_MAGIC_2 UINT8_C(0x41) /* A */
#define TL_APP_CATALOG_WIRE_MAGIC_3 UINT8_C(0x43) /* C */
#define TL_APP_CATALOG_WIRE_MAJOR UINT16_C(1)
#define TL_APP_CATALOG_WIRE_MINOR UINT16_C(0)

#define TL_APP_CATALOG_WIRE_HEADER_SIZE UINT32_C(128)
#define TL_APP_CATALOG_WIRE_TABLE_DESCRIPTOR_SIZE UINT32_C(24)
#define TL_APP_CATALOG_WIRE_TABLE_DESCRIPTOR_OFFSET UINT32_C(32)
#define TL_APP_CATALOG_WIRE_TABLE_COUNT UINT32_C(4)
#define TL_APP_CATALOG_WIRE_TABLE_FLAG_VARIABLE_RECORDS UINT32_C(1)

#define TL_APP_CATALOG_WIRE_HEADER_MAGIC_OFFSET UINT32_C(0)
#define TL_APP_CATALOG_WIRE_HEADER_MAJOR_OFFSET UINT32_C(4)
#define TL_APP_CATALOG_WIRE_HEADER_MINOR_OFFSET UINT32_C(6)
#define TL_APP_CATALOG_WIRE_HEADER_SIZE_OFFSET UINT32_C(8)
#define TL_APP_CATALOG_WIRE_HEADER_TOTAL_SIZE_OFFSET UINT32_C(12)
#define TL_APP_CATALOG_WIRE_HEADER_TABLE_COUNT_OFFSET UINT32_C(20)
#define TL_APP_CATALOG_WIRE_HEADER_FLAGS_OFFSET UINT32_C(24)
#define TL_APP_CATALOG_WIRE_HEADER_RESERVED_OFFSET UINT32_C(28)

#define TL_APP_CATALOG_WIRE_DESCRIPTOR_OFFSET_FIELD UINT32_C(0)
#define TL_APP_CATALOG_WIRE_DESCRIPTOR_COUNT_FIELD UINT32_C(8)
#define TL_APP_CATALOG_WIRE_DESCRIPTOR_STRIDE_FIELD UINT32_C(16)
#define TL_APP_CATALOG_WIRE_DESCRIPTOR_FLAGS_FIELD UINT32_C(20)

#define TL_APP_CATALOG_WIRE_TABLE_INFO UINT32_C(0)
#define TL_APP_CATALOG_WIRE_TABLE_APPS UINT32_C(1)
#define TL_APP_CATALOG_WIRE_TABLE_ARGS UINT32_C(2)
#define TL_APP_CATALOG_WIRE_TABLE_STRINGS UINT32_C(3)

#define TL_APP_CATALOG_WIRE_INFO_STRIDE UINT32_C(32)
#define TL_APP_CATALOG_WIRE_APP_STRIDE UINT32_C(192)
#define TL_APP_CATALOG_WIRE_ARG_STRIDE UINT32_C(16)
#define TL_APP_CATALOG_WIRE_STRING_RECORD_HEADER_SIZE UINT32_C(8)
#define TL_APP_CATALOG_WIRE_STRING_REF_SIZE UINT32_C(16)

#define TL_APP_CATALOG_WIRE_INFO_VERSION_OFFSET UINT32_C(0)
#define TL_APP_CATALOG_WIRE_INFO_FLAGS_OFFSET UINT32_C(4)
#define TL_APP_CATALOG_WIRE_INFO_APP_COUNT_OFFSET UINT32_C(8)
#define TL_APP_CATALOG_WIRE_INFO_ARG_COUNT_OFFSET UINT32_C(16)
#define TL_APP_CATALOG_WIRE_INFO_RESERVED_OFFSET UINT32_C(24)

#define TL_APP_CATALOG_WIRE_APP_ID_OFFSET UINT32_C(0)
#define TL_APP_CATALOG_WIRE_APP_NAME_OFFSET UINT32_C(16)
#define TL_APP_CATALOG_WIRE_APP_EXECUTABLE_PATH_OFFSET UINT32_C(32)
#define TL_APP_CATALOG_WIRE_APP_PREFIX_PATH_OFFSET UINT32_C(48)
#define TL_APP_CATALOG_WIRE_APP_ICON_PATH_OFFSET UINT32_C(64)
#define TL_APP_CATALOG_WIRE_APP_WORKING_DIRECTORY_OFFSET UINT32_C(80)
#define TL_APP_CATALOG_WIRE_APP_SHA256_OFFSET UINT32_C(96)
#define TL_APP_CATALOG_WIRE_APP_VERSION_OFFSET UINT32_C(112)
#define TL_APP_CATALOG_WIRE_APP_CREATED_AT_OFFSET UINT32_C(128)
#define TL_APP_CATALOG_WIRE_APP_ARGS_INDEX_OFFSET UINT32_C(144)
#define TL_APP_CATALOG_WIRE_APP_ARGS_COUNT_OFFSET UINT32_C(152)
#define TL_APP_CATALOG_WIRE_APP_CPU_LIMIT_OFFSET UINT32_C(160)
#define TL_APP_CATALOG_WIRE_APP_MEMORY_LIMIT_OFFSET UINT32_C(168)
#define TL_APP_CATALOG_WIRE_APP_RESERVED_OFFSET UINT32_C(176)

#define TL_APP_CATALOG_WIRE_ARG_STRING_OFFSET UINT32_C(0)

#define TL_APP_CATALOG_LIMIT_MAX_INPUT_BYTES UINT64_C(4194304)
#define TL_APP_CATALOG_LIMIT_MAX_APPS UINT64_C(65535)
#define TL_APP_CATALOG_LIMIT_MAX_ARGS UINT64_C(262144)
#define TL_APP_CATALOG_LIMIT_MAX_STRINGS UINT64_C(1048576)
#define TL_APP_CATALOG_LIMIT_MAX_STRING_BYTES UINT64_C(1048576)
#define TL_APP_CATALOG_LIMIT_MAX_DECODED_STRING_BYTES UINT64_C(16777216)
#define TL_APP_CATALOG_LIMIT_MAX_SERIALIZED_BYTES UINT64_C(67108864)

/* All pointers are transient caller-owned memory and are never retained. */
tl_app_catalog_status_t tl_app_catalog_parse_v1_size(
    const uint8_t* input,
    uint64_t input_length,
    uint64_t* output_required,
    tl_app_catalog_error_v1* error,
    char* error_message,
    uint64_t error_capacity,
    uint64_t* error_required);

tl_app_catalog_status_t tl_app_catalog_parse_v1_fill(
    const uint8_t* input,
    uint64_t input_length,
    uint8_t* output,
    uint64_t output_capacity,
    uint64_t* output_required,
    tl_app_catalog_error_v1* error,
    char* error_message,
    uint64_t error_capacity,
    uint64_t* error_required);

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif  /* TRADUTORLINUX_FFI_RUST_APP_CATALOG_PARSER_H */
