#include "kernel32_common.hpp"
#include "tradutorlinux/loader/builtin_modules.hpp"
#include "tradutorlinux/loader/module.hpp"
#include "tradutorlinux/runtime/msvcrt.hpp"

namespace tradutorlinux::loader {

void register_kernel32_module() {
    static const ExportedFunction kKernel32Exports[] = {
        {"GetStdHandle", 1, reinterpret_cast<std::uintptr_t>(&tl_GetStdHandle), ExportSupport::Full},
        {"WriteFile", 2, reinterpret_cast<std::uintptr_t>(&tl_WriteFile), ExportSupport::Full},
        {"ReadFile", 3, reinterpret_cast<std::uintptr_t>(&tl_ReadFile), ExportSupport::Full},
        {"ExitProcess", 4, reinterpret_cast<std::uintptr_t>(&tl_ExitProcess), ExportSupport::Full},
        {"GetLastError", 5, reinterpret_cast<std::uintptr_t>(&tl_GetLastError), ExportSupport::Full},
        {"SetLastError", 6, reinterpret_cast<std::uintptr_t>(&tl_SetLastError), ExportSupport::Full},
        {"VirtualAlloc", 7, reinterpret_cast<std::uintptr_t>(&tl_VirtualAlloc), ExportSupport::Full},
        {"VirtualFree", 8, reinterpret_cast<std::uintptr_t>(&tl_VirtualFree), ExportSupport::Full},
        {"CreateFileA", 9, reinterpret_cast<std::uintptr_t>(&tl_CreateFileA), ExportSupport::Full},
        {"CreateFileW", 69, reinterpret_cast<std::uintptr_t>(&tl_CreateFileW), ExportSupport::Full},
        {"CloseHandle", 10, reinterpret_cast<std::uintptr_t>(&tl_CloseHandle), ExportSupport::Full},
        {"DeleteCriticalSection", 11, reinterpret_cast<std::uintptr_t>(&tl_DeleteCriticalSection), ExportSupport::Full},
        {"EnterCriticalSection", 12, reinterpret_cast<std::uintptr_t>(&tl_EnterCriticalSection), ExportSupport::Full},
        {"GetConsoleMode", 13, reinterpret_cast<std::uintptr_t>(&tl_GetConsoleMode), ExportSupport::Full},
        {"InitializeCriticalSection", 14, reinterpret_cast<std::uintptr_t>(&tl_InitializeCriticalSection), ExportSupport::Full},
        {"IsDBCSLeadByteEx", 15, reinterpret_cast<std::uintptr_t>(&tl_IsDBCSLeadByteEx), ExportSupport::Full},
        {"LeaveCriticalSection", 16, reinterpret_cast<std::uintptr_t>(&tl_LeaveCriticalSection), ExportSupport::Full},
        {"MultiByteToWideChar", 17, reinterpret_cast<std::uintptr_t>(&tl_MultiByteToWideChar), ExportSupport::Full},
        {"SetConsoleMode", 18, reinterpret_cast<std::uintptr_t>(&tl_SetConsoleMode), ExportSupport::Full},
        {"SetUnhandledExceptionFilter", 19, reinterpret_cast<std::uintptr_t>(&tl_SetUnhandledExceptionFilter), ExportSupport::Full},
        {"Sleep", 20, reinterpret_cast<std::uintptr_t>(&tl_Sleep), ExportSupport::Full},
        {"TlsGetValue", 21, reinterpret_cast<std::uintptr_t>(&tl_TlsGetValue), ExportSupport::Full},
        {"VirtualProtect", 22, reinterpret_cast<std::uintptr_t>(&tl_VirtualProtect), ExportSupport::Full},
        {"VirtualQuery", 23, reinterpret_cast<std::uintptr_t>(&tl_VirtualQuery), ExportSupport::Full},
        {"WideCharToMultiByte", 24, reinterpret_cast<std::uintptr_t>(&tl_WideCharToMultiByte), ExportSupport::Full},
        {"GetModuleHandleA", 25, reinterpret_cast<std::uintptr_t>(&tl_GetModuleHandleA), ExportSupport::Full},
        {"GetModuleHandleW", 26, reinterpret_cast<std::uintptr_t>(&tl_GetModuleHandleW), ExportSupport::Full},
        {"GetProcAddress", 27, reinterpret_cast<std::uintptr_t>(&tl_GetProcAddress), ExportSupport::Full},
        {"GetCommandLineA", 28, reinterpret_cast<std::uintptr_t>(&tl_GetCommandLineA), ExportSupport::Full},
        {"GetCommandLineW", 29, reinterpret_cast<std::uintptr_t>(&tl_GetCommandLineW), ExportSupport::Full},
        {"GetEnvironmentVariableA", 30, reinterpret_cast<std::uintptr_t>(&tl_GetEnvironmentVariableA), ExportSupport::Full},
        {"GetEnvironmentVariableW", 31, reinterpret_cast<std::uintptr_t>(&tl_GetEnvironmentVariableW), ExportSupport::Full},
        {"GetProcessHeap", 32, reinterpret_cast<std::uintptr_t>(&tl_GetProcessHeap), ExportSupport::Full},
        {"HeapAlloc", 33, reinterpret_cast<std::uintptr_t>(&tl_HeapAlloc), ExportSupport::Full},
        {"HeapFree", 34, reinterpret_cast<std::uintptr_t>(&tl_HeapFree), ExportSupport::Full},
        {"HeapReAlloc", 35, reinterpret_cast<std::uintptr_t>(&tl_HeapReAlloc), ExportSupport::Full},
        {"GetTickCount64", 36, reinterpret_cast<std::uintptr_t>(&tl_GetTickCount64), ExportSupport::Full},
        {"GetSystemTimeAsFileTime", 37, reinterpret_cast<std::uintptr_t>(&tl_GetSystemTimeAsFileTime), ExportSupport::Full},
        {"GetFileSize", 38, reinterpret_cast<std::uintptr_t>(&tl_GetFileSize), ExportSupport::Full},
        {"SetFilePointer", 39, reinterpret_cast<std::uintptr_t>(&tl_SetFilePointer), ExportSupport::Full},
        {"GetFileAttributesA", 40, reinterpret_cast<std::uintptr_t>(&tl_GetFileAttributesA), ExportSupport::Full},
        {"DeleteFileA", 41, reinterpret_cast<std::uintptr_t>(&tl_DeleteFileA), ExportSupport::Full},
        {"MoveFileA", 42, reinterpret_cast<std::uintptr_t>(&tl_MoveFileA), ExportSupport::Full},
        {"CreateDirectoryA", 43, reinterpret_cast<std::uintptr_t>(&tl_CreateDirectoryA), ExportSupport::Full},
        {"FindFirstFileA", 44, reinterpret_cast<std::uintptr_t>(&tl_FindFirstFileA), ExportSupport::Full},
        {"FindNextFileA", 45, reinterpret_cast<std::uintptr_t>(&tl_FindNextFileA), ExportSupport::Full},
        {"FindClose", 46, reinterpret_cast<std::uintptr_t>(&tl_FindClose), ExportSupport::Full},
        {"GetCurrentDirectoryA", 47, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentDirectoryA), ExportSupport::Full},
        {"GetCurrentDirectoryW", 48, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentDirectoryW), ExportSupport::Full},
        {"GetModuleFileNameA", 49, reinterpret_cast<std::uintptr_t>(&tl_GetModuleFileNameA), ExportSupport::Full},
        {"GetModuleFileNameW", 193, reinterpret_cast<std::uintptr_t>(&tl_GetModuleFileNameW), ExportSupport::Full},
        // Fase 11: ConcorrÃªncia.
        {"TlsAlloc", 50, reinterpret_cast<std::uintptr_t>(&tl_TlsAlloc), ExportSupport::Full},
        {"TlsSetValue", 51, reinterpret_cast<std::uintptr_t>(&tl_TlsSetValue), ExportSupport::Full},
        {"TlsFree", 52, reinterpret_cast<std::uintptr_t>(&tl_TlsFree), ExportSupport::Full},
        {"CreateThread", 53, reinterpret_cast<std::uintptr_t>(&tl_CreateThread), ExportSupport::Full},
        {"ExitThread", 54, reinterpret_cast<std::uintptr_t>(&tl_ExitThread), ExportSupport::Full},
        {"WaitForSingleObject", 55, reinterpret_cast<std::uintptr_t>(&tl_WaitForSingleObject), ExportSupport::Full},
        {"GetCurrentThreadId", 56, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentThreadId), ExportSupport::Full},
        {"GetCurrentProcessId", 57, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentProcessId), ExportSupport::Full},
        // Fase 10+: variantes wide do sistema de arquivos e console.
        {"GetFileAttributesW", 58, reinterpret_cast<std::uintptr_t>(&tl_GetFileAttributesW), ExportSupport::Full},
        {"FindFirstFileW", 59, reinterpret_cast<std::uintptr_t>(&tl_FindFirstFileW), ExportSupport::Full},
        {"FindNextFileW", 60, reinterpret_cast<std::uintptr_t>(&tl_FindNextFileW), ExportSupport::Full},
        {"FormatMessageW", 61, reinterpret_cast<std::uintptr_t>(&tl_FormatMessageW), ExportSupport::Full},
        {"FormatMessageA", 237, reinterpret_cast<std::uintptr_t>(&tl_FormatMessageA), ExportSupport::Full},
        {"AreFileApisANSI", 238, reinterpret_cast<std::uintptr_t>(&tl_AreFileApisANSI), ExportSupport::Full},
        {"GetConsoleOutputCP", 62, reinterpret_cast<std::uintptr_t>(&tl_GetConsoleOutputCP), ExportSupport::Full},
        {"GetTempFileNameW", 63, reinterpret_cast<std::uintptr_t>(&tl_GetTempFileNameW), ExportSupport::Full},
        {"LocalFree", 64, reinterpret_cast<std::uintptr_t>(&tl_LocalFree), ExportSupport::Full},
        {"SetConsoleOutputCP", 65, reinterpret_cast<std::uintptr_t>(&tl_SetConsoleOutputCP), ExportSupport::Full},
        {"CreateMutexA", 66, reinterpret_cast<std::uintptr_t>(&tl_CreateMutexA), ExportSupport::Full},
        {"GetStartupInfoA", 67, reinterpret_cast<std::uintptr_t>(&tl_GetStartupInfoA), ExportSupport::Full},
        {"MulDiv", 68, reinterpret_cast<std::uintptr_t>(&tl_MulDiv), ExportSupport::Full},
        {"GetFileSizeEx", 70, reinterpret_cast<std::uintptr_t>(&tl_GetFileSizeEx), ExportSupport::Full},
        {"SetFilePointerEx", 71, reinterpret_cast<std::uintptr_t>(&tl_SetFilePointerEx), ExportSupport::Full},
        {"SetEndOfFile", 72, reinterpret_cast<std::uintptr_t>(&tl_SetEndOfFile), ExportSupport::Full},
        {"FlushFileBuffers", 73, reinterpret_cast<std::uintptr_t>(&tl_FlushFileBuffers), ExportSupport::Full},
        {"GetFileAttributesExW", 74, reinterpret_cast<std::uintptr_t>(&tl_GetFileAttributesExW), ExportSupport::Full},
        {"DeleteFileW", 75, reinterpret_cast<std::uintptr_t>(&tl_DeleteFileW), ExportSupport::Full},
        {"MoveFileW", 76, reinterpret_cast<std::uintptr_t>(&tl_MoveFileW), ExportSupport::Full},
        {"MoveFileExW", 77, reinterpret_cast<std::uintptr_t>(&tl_MoveFileExW), ExportSupport::Full},
        {"CopyFileW", 78, reinterpret_cast<std::uintptr_t>(&tl_CopyFileW), ExportSupport::Full},
        {"CreateDirectoryW", 79, reinterpret_cast<std::uintptr_t>(&tl_CreateDirectoryW), ExportSupport::Full},
        {"RemoveDirectoryW", 80, reinterpret_cast<std::uintptr_t>(&tl_RemoveDirectoryW), ExportSupport::Full},
        {"GetTempPathW", 81, reinterpret_cast<std::uintptr_t>(&tl_GetTempPathW), ExportSupport::Full},
        {"GetFullPathNameW", 82, reinterpret_cast<std::uintptr_t>(&tl_GetFullPathNameW), ExportSupport::Full},
        {"GetFullPathNameA", 171, reinterpret_cast<std::uintptr_t>(&tl_GetFullPathNameA), ExportSupport::Full},
        {"GetFileTime", 83, reinterpret_cast<std::uintptr_t>(&tl_GetFileTime), ExportSupport::Full},
        {"SetFileTime", 84, reinterpret_cast<std::uintptr_t>(&tl_SetFileTime), ExportSupport::Full},
        {"GetFileInformationByHandle", 85,
         reinterpret_cast<std::uintptr_t>(&tl_GetFileInformationByHandle), ExportSupport::Full},
        {"GetFileInformationByHandleEx", 86,
         reinterpret_cast<std::uintptr_t>(&tl_GetFileInformationByHandleEx), ExportSupport::Full},
        {"GetFinalPathNameByHandleW", 87,
         reinterpret_cast<std::uintptr_t>(&tl_GetFinalPathNameByHandleW), ExportSupport::Full},
        {"FindResourceW", 88, reinterpret_cast<std::uintptr_t>(&tl_FindResourceW), ExportSupport::Full},
        {"LoadResource", 89, reinterpret_cast<std::uintptr_t>(&tl_LoadResource), ExportSupport::Full},
        {"LockResource", 90, reinterpret_cast<std::uintptr_t>(&tl_LockResource), ExportSupport::Full},
        {"SizeofResource", 91, reinterpret_cast<std::uintptr_t>(&tl_SizeofResource), ExportSupport::Full},
        {"CreateMutexW", 92, reinterpret_cast<std::uintptr_t>(&tl_CreateMutexW), ExportSupport::Full},
        {"CreateEventA", 93, reinterpret_cast<std::uintptr_t>(&tl_CreateEventA), ExportSupport::Full},
        {"CreateEventW", 94, reinterpret_cast<std::uintptr_t>(&tl_CreateEventW), ExportSupport::Full},
        {"SetEvent", 95, reinterpret_cast<std::uintptr_t>(&tl_SetEvent), ExportSupport::Full},
        {"ResetEvent", 96, reinterpret_cast<std::uintptr_t>(&tl_ResetEvent), ExportSupport::Full},
        {"ReleaseMutex", 101, reinterpret_cast<std::uintptr_t>(&tl_ReleaseMutex), ExportSupport::Full},
        {"CreateProcessW", 102, reinterpret_cast<std::uintptr_t>(&tl_CreateProcessW), ExportSupport::Full},
        {"GetExitCodeProcess", 103,
         reinterpret_cast<std::uintptr_t>(&tl_GetExitCodeProcess), ExportSupport::Full},
        {"TerminateProcess", 104, reinterpret_cast<std::uintptr_t>(&tl_TerminateProcess), ExportSupport::Full},
        {"CreateSemaphoreA", 97, reinterpret_cast<std::uintptr_t>(&tl_CreateSemaphoreA), ExportSupport::Full},
        {"CreateSemaphoreW", 98, reinterpret_cast<std::uintptr_t>(&tl_CreateSemaphoreW), ExportSupport::Full},
        {"ReleaseSemaphore", 99, reinterpret_cast<std::uintptr_t>(&tl_ReleaseSemaphore), ExportSupport::Full},
        {"WaitForMultipleObjects", 100,
         reinterpret_cast<std::uintptr_t>(&tl_WaitForMultipleObjects), ExportSupport::Full},
        {"QueryPerformanceCounter", 105, reinterpret_cast<std::uintptr_t>(&tl_QueryPerformanceCounter), ExportSupport::Full},
        {"QueryPerformanceFrequency", 106, reinterpret_cast<std::uintptr_t>(&tl_QueryPerformanceFrequency), ExportSupport::Full},
        {"GetSystemInfo", 107, reinterpret_cast<std::uintptr_t>(&tl_GetSystemInfo), ExportSupport::Full},
        {"GetNativeSystemInfo", 108, reinterpret_cast<std::uintptr_t>(&tl_GetNativeSystemInfo), ExportSupport::Full},
        {"GlobalMemoryStatusEx", 109, reinterpret_cast<std::uintptr_t>(&tl_GlobalMemoryStatusEx), ExportSupport::Full},
        {"CreateFileMappingA", 110, reinterpret_cast<std::uintptr_t>(&tl_CreateFileMappingA), ExportSupport::Full},
        {"CreateFileMappingW", 111, reinterpret_cast<std::uintptr_t>(&tl_CreateFileMappingW), ExportSupport::Full},
        {"MapViewOfFile", 112, reinterpret_cast<std::uintptr_t>(&tl_MapViewOfFile), ExportSupport::Full},
        {"UnmapViewOfFile", 113, reinterpret_cast<std::uintptr_t>(&tl_UnmapViewOfFile), ExportSupport::Full},
        {"FlushViewOfFile", 114, reinterpret_cast<std::uintptr_t>(&tl_FlushViewOfFile), ExportSupport::Full},
        {"GetDiskFreeSpaceExA", 115, reinterpret_cast<std::uintptr_t>(&tl_GetDiskFreeSpaceExA), ExportSupport::Full},
        {"GetDiskFreeSpaceExW", 116, reinterpret_cast<std::uintptr_t>(&tl_GetDiskFreeSpaceExW), ExportSupport::Full},
        {"GetDriveTypeA", 117, reinterpret_cast<std::uintptr_t>(&tl_GetDriveTypeA), ExportSupport::Full},
        {"GetDriveTypeW", 118, reinterpret_cast<std::uintptr_t>(&tl_GetDriveTypeW), ExportSupport::Full},
        {"GetVolumeInformationA", 119, reinterpret_cast<std::uintptr_t>(&tl_GetVolumeInformationA), ExportSupport::Full},
        {"GetVolumeInformationW", 120, reinterpret_cast<std::uintptr_t>(&tl_GetVolumeInformationW), ExportSupport::Full},
        {"GetSystemTime", 121, reinterpret_cast<std::uintptr_t>(&tl_GetSystemTime), ExportSupport::Full},
        {"GetLocalTime", 122, reinterpret_cast<std::uintptr_t>(&tl_GetLocalTime), ExportSupport::Full},
        {"FileTimeToSystemTime", 123, reinterpret_cast<std::uintptr_t>(&tl_FileTimeToSystemTime), ExportSupport::Full},
        {"SystemTimeToFileTime", 124, reinterpret_cast<std::uintptr_t>(&tl_SystemTimeToFileTime), ExportSupport::Full},
        {"CompareStringA", 125, reinterpret_cast<std::uintptr_t>(&tl_CompareStringA), ExportSupport::Full},
        {"CompareStringW", 126, reinterpret_cast<std::uintptr_t>(&tl_CompareStringW), ExportSupport::Full},
        {"GetUserDefaultLCID", 127, reinterpret_cast<std::uintptr_t>(&tl_GetUserDefaultLCID), ExportSupport::Full},
        {"GetSystemDefaultLCID", 128, reinterpret_cast<std::uintptr_t>(&tl_GetSystemDefaultLCID), ExportSupport::Full},
        {"GetComputerNameA", 129, reinterpret_cast<std::uintptr_t>(&tl_GetComputerNameA), ExportSupport::Full},
        {"GetComputerNameW", 130, reinterpret_cast<std::uintptr_t>(&tl_GetComputerNameW), ExportSupport::Full},
        {"InitializeSRWLock", 131, reinterpret_cast<std::uintptr_t>(&tl_InitializeSRWLock), ExportSupport::Full},
        {"AcquireSRWLockExclusive", 132, reinterpret_cast<std::uintptr_t>(&tl_AcquireSRWLockExclusive), ExportSupport::Full},
        {"ReleaseSRWLockExclusive", 133, reinterpret_cast<std::uintptr_t>(&tl_ReleaseSRWLockExclusive), ExportSupport::Full},
        {"AcquireSRWLockShared", 134, reinterpret_cast<std::uintptr_t>(&tl_AcquireSRWLockShared), ExportSupport::Full},
        {"ReleaseSRWLockShared", 135, reinterpret_cast<std::uintptr_t>(&tl_ReleaseSRWLockShared), ExportSupport::Full},
        {"SleepConditionVariableSRW", 136, reinterpret_cast<std::uintptr_t>(&tl_SleepConditionVariableSRW), ExportSupport::Full},
        {"WakeConditionVariable", 137, reinterpret_cast<std::uintptr_t>(&tl_WakeConditionVariable), ExportSupport::Full},
        {"WakeAllConditionVariable", 138, reinterpret_cast<std::uintptr_t>(&tl_WakeAllConditionVariable), ExportSupport::Full},
        {"AddVectoredExceptionHandler", 139, reinterpret_cast<std::uintptr_t>(&tl_AddVectoredExceptionHandler), ExportSupport::Full},
        {"RemoveVectoredExceptionHandler", 140, reinterpret_cast<std::uintptr_t>(&tl_RemoveVectoredExceptionHandler), ExportSupport::Full},
        {"RaiseException", 141, reinterpret_cast<std::uintptr_t>(&tl_RaiseException), ExportSupport::Full},
        {"GetPrivateProfileStringA", 142, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileStringA), ExportSupport::Full},
        {"GetPrivateProfileStringW", 143, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileStringW), ExportSupport::Full},
        {"GetPrivateProfileIntA", 144, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileIntA), ExportSupport::Full},
        {"GetPrivateProfileIntW", 145, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileIntW), ExportSupport::Full},
        {"WritePrivateProfileStringA", 146, reinterpret_cast<std::uintptr_t>(&tl_WritePrivateProfileStringA), ExportSupport::Full},
        {"WritePrivateProfileStringW", 147, reinterpret_cast<std::uintptr_t>(&tl_WritePrivateProfileStringW), ExportSupport::Full},
        {"GetPrivateProfileSectionA", 148, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileSectionA), ExportSupport::Full},
        {"GetPrivateProfileSectionW", 149, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileSectionW), ExportSupport::Full},
        {"GetConsoleScreenBufferInfo", 150, reinterpret_cast<std::uintptr_t>(&tl_GetConsoleScreenBufferInfo), ExportSupport::Full},
        {"SetConsoleTextAttribute", 151, reinterpret_cast<std::uintptr_t>(&tl_SetConsoleTextAttribute), ExportSupport::Full},
        {"CreateThreadpoolWork", 152, reinterpret_cast<std::uintptr_t>(&tl_CreateThreadpoolWork), ExportSupport::Full},
        {"SubmitThreadpoolWork", 153, reinterpret_cast<std::uintptr_t>(&tl_SubmitThreadpoolWork), ExportSupport::Full},
        {"WaitForThreadpoolWorkCallbacks", 154, reinterpret_cast<std::uintptr_t>(&tl_WaitForThreadpoolWorkCallbacks), ExportSupport::Full},
        {"CloseThreadpoolWork", 155, reinterpret_cast<std::uintptr_t>(&tl_CloseThreadpoolWork), ExportSupport::Full},
        {"CreateThreadpoolTimer", 156, reinterpret_cast<std::uintptr_t>(&tl_CreateThreadpoolTimer), ExportSupport::Full},
        {"SetThreadpoolTimer", 157, reinterpret_cast<std::uintptr_t>(&tl_SetThreadpoolTimer), ExportSupport::Full},
        {"WaitForThreadpoolTimerCallbacks", 158, reinterpret_cast<std::uintptr_t>(&tl_WaitForThreadpoolTimerCallbacks), ExportSupport::Full},
        {"CloseThreadpoolTimer", 159, reinterpret_cast<std::uintptr_t>(&tl_CloseThreadpoolTimer), ExportSupport::Full},
        {"ConvertThreadToFiber", 160, reinterpret_cast<std::uintptr_t>(&tl_ConvertThreadToFiber), ExportSupport::Full},
        {"ConvertThreadToFiberEx", 188, reinterpret_cast<std::uintptr_t>(&tl_ConvertThreadToFiberEx), ExportSupport::Full},
        {"ConvertFiberToThread", 161, reinterpret_cast<std::uintptr_t>(&tl_ConvertFiberToThread), ExportSupport::Full},
        {"CreateFiber", 162, reinterpret_cast<std::uintptr_t>(&tl_CreateFiber), ExportSupport::Full},
        {"CreateFiberEx", 189, reinterpret_cast<std::uintptr_t>(&tl_CreateFiberEx), ExportSupport::Full},
        {"SwitchToFiber", 163, reinterpret_cast<std::uintptr_t>(&tl_SwitchToFiber), ExportSupport::Full},
        {"DeleteFiber", 164, reinterpret_cast<std::uintptr_t>(&tl_DeleteFiber), ExportSupport::Full},
        {"GetFiberData", 165, reinterpret_cast<std::uintptr_t>(&tl_GetFiberData), ExportSupport::Full},
        {"CreateToolhelp32Snapshot", 190, reinterpret_cast<std::uintptr_t>(&tl_CreateToolhelp32Snapshot), ExportSupport::Full},
        {"Process32FirstW", 191, reinterpret_cast<std::uintptr_t>(&tl_Process32FirstW), ExportSupport::Full},
        {"Process32NextW", 192, reinterpret_cast<std::uintptr_t>(&tl_Process32NextW), ExportSupport::Full},
        {"OpenProcess", 193, reinterpret_cast<std::uintptr_t>(&tl_OpenProcess), ExportSupport::Full},
        {"HeapCreate", 166, reinterpret_cast<std::uintptr_t>(&tl_HeapCreate), ExportSupport::Full},
        {"HeapDestroy", 167, reinterpret_cast<std::uintptr_t>(&tl_HeapDestroy), ExportSupport::Full},
        {"HeapValidate", 168, reinterpret_cast<std::uintptr_t>(&tl_HeapValidate), ExportSupport::Full},
        {"HeapSize", 169, reinterpret_cast<std::uintptr_t>(&tl_HeapSize), ExportSupport::Full},
        {"HeapCompact", 170, reinterpret_cast<std::uintptr_t>(&tl_HeapCompact), ExportSupport::Full},
        {"LoadLibraryA", 172, reinterpret_cast<std::uintptr_t>(&tl_LoadLibraryA), ExportSupport::Full},
        {"LoadLibraryW", 173, reinterpret_cast<std::uintptr_t>(&tl_LoadLibraryW), ExportSupport::Full},
        {"LoadLibraryExA", 174, reinterpret_cast<std::uintptr_t>(&tl_LoadLibraryExA), ExportSupport::Full},
        {"LoadLibraryExW", 175, reinterpret_cast<std::uintptr_t>(&tl_LoadLibraryExW), ExportSupport::Full},
        {"FreeLibrary", 176, reinterpret_cast<std::uintptr_t>(&tl_FreeLibrary), ExportSupport::Full},
        {"GetModuleHandleExA", 177, reinterpret_cast<std::uintptr_t>(&tl_GetModuleHandleExA), ExportSupport::Full},
        {"GetModuleHandleExW", 178, reinterpret_cast<std::uintptr_t>(&tl_GetModuleHandleExW), ExportSupport::Full},
        {"GetVersionExA", 179, reinterpret_cast<std::uintptr_t>(&tl_GetVersionExA), ExportSupport::Full},
        {"GetVersionExW", 180, reinterpret_cast<std::uintptr_t>(&tl_GetVersionExW), ExportSupport::Full},
        {"VerifyVersionInfoW", 181, reinterpret_cast<std::uintptr_t>(&tl_VerifyVersionInfoW), ExportSupport::Full},
        {"VerSetConditionMask", 182, reinterpret_cast<std::uintptr_t>(&tl_VerSetConditionMask), ExportSupport::Full},
        {"GetUserDefaultLocaleName", 183, reinterpret_cast<std::uintptr_t>(&tl_GetUserDefaultLocaleName), ExportSupport::Full},
        {"LocaleNameToLCID", 184, reinterpret_cast<std::uintptr_t>(&tl_LocaleNameToLCID), ExportSupport::Full},
        {"WaitOnAddress", 185, reinterpret_cast<std::uintptr_t>(&tl_WaitOnAddress), ExportSupport::Full},
        {"WakeByAddressSingle", 186, reinterpret_cast<std::uintptr_t>(&tl_WakeByAddressSingle), ExportSupport::Full},
        {"WakeByAddressAll", 187, reinterpret_cast<std::uintptr_t>(&tl_WakeByAddressAll), ExportSupport::Full},
        {"GetCurrentProcess", 194, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentProcess), ExportSupport::Full},
        {"RtlCaptureContext", 195, reinterpret_cast<std::uintptr_t>(&tl_RtlCaptureContext), ExportSupport::Full},
        {"RtlLookupFunctionEntry", 196, reinterpret_cast<std::uintptr_t>(&tl_RtlLookupFunctionEntry), ExportSupport::Full},
        {"RtlVirtualUnwind", 197, reinterpret_cast<std::uintptr_t>(&tl_RtlVirtualUnwind), ExportSupport::Full},
        {"RtlPcToFileHeader", 198, reinterpret_cast<std::uintptr_t>(&tl_RtlPcToFileHeader), ExportSupport::Full},
        {"RtlUnwind", 199, reinterpret_cast<std::uintptr_t>(&tl_RtlUnwind), ExportSupport::Full},
        {"RtlUnwindEx", 200, reinterpret_cast<std::uintptr_t>(&tl_RtlUnwindEx), ExportSupport::Full},
        {"UnhandledExceptionFilter", 201, reinterpret_cast<std::uintptr_t>(&tl_UnhandledExceptionFilter), ExportSupport::Full},
        {"SetEnvironmentVariableW", 202, reinterpret_cast<std::uintptr_t>(&tl_SetEnvironmentVariableW), ExportSupport::Full},
        {"GetEnvironmentStringsW", 203, reinterpret_cast<std::uintptr_t>(&tl_GetEnvironmentStringsW), ExportSupport::Full},
        {"FreeEnvironmentStringsW", 204, reinterpret_cast<std::uintptr_t>(&tl_FreeEnvironmentStringsW), ExportSupport::Full},
        {"ExpandEnvironmentStringsW", 205, reinterpret_cast<std::uintptr_t>(&tl_ExpandEnvironmentStringsW), ExportSupport::Full},
        {"FlsAlloc", 206, reinterpret_cast<std::uintptr_t>(&tl_FlsAlloc), ExportSupport::Full},
        {"FlsFree", 207, reinterpret_cast<std::uintptr_t>(&tl_FlsFree), ExportSupport::Full},
        {"FlsGetValue", 208, reinterpret_cast<std::uintptr_t>(&tl_FlsGetValue), ExportSupport::Full},
        {"FlsSetValue", 209, reinterpret_cast<std::uintptr_t>(&tl_FlsSetValue), ExportSupport::Full},
        {"GetACP", 210, reinterpret_cast<std::uintptr_t>(&tl_GetACP), ExportSupport::Full},
        {"GetOEMCP", 211, reinterpret_cast<std::uintptr_t>(&tl_GetOEMCP), ExportSupport::Full},
        {"GetCPInfo", 212, reinterpret_cast<std::uintptr_t>(&tl_GetCPInfo), ExportSupport::Full},
        {"GetLocaleInfoW", 213, reinterpret_cast<std::uintptr_t>(&tl_GetLocaleInfoW), ExportSupport::Full},
        {"LCMapStringW", 214, reinterpret_cast<std::uintptr_t>(&tl_LCMapStringW), ExportSupport::Full},
        {"LCMapStringEx", 215, reinterpret_cast<std::uintptr_t>(&tl_LCMapStringEx), ExportSupport::Full},
        {"GetLocaleInfoEx", 216, reinterpret_cast<std::uintptr_t>(&tl_GetLocaleInfoEx), ExportSupport::Full},
        {"IsValidLocale", 217, reinterpret_cast<std::uintptr_t>(&tl_IsValidLocale), ExportSupport::Full},
        {"IsValidCodePage", 218, reinterpret_cast<std::uintptr_t>(&tl_IsValidCodePage), ExportSupport::Full},
        {"EnumSystemLocalesW", 219, reinterpret_cast<std::uintptr_t>(&tl_EnumSystemLocalesW), ExportSupport::Full},
        {"GetStringTypeW", 220, reinterpret_cast<std::uintptr_t>(&tl_GetStringTypeW), ExportSupport::Full},
        {"GetDateFormatW", 221, reinterpret_cast<std::uintptr_t>(&tl_GetDateFormatW), ExportSupport::Full},
        {"GetTimeFormatW", 222, reinterpret_cast<std::uintptr_t>(&tl_GetTimeFormatW), ExportSupport::Full},
        {"GetStartupInfoW", 223, reinterpret_cast<std::uintptr_t>(&tl_GetStartupInfoW), ExportSupport::Full},
        {"GetSystemDirectoryW", 224, reinterpret_cast<std::uintptr_t>(&tl_GetSystemDirectoryW), ExportSupport::Full},
        {"GetFileType", 225, reinterpret_cast<std::uintptr_t>(&tl_GetFileType), ExportSupport::Full},
        {"SetStdHandle", 226, reinterpret_cast<std::uintptr_t>(&tl_SetStdHandle), ExportSupport::Full},
        {"ReadConsoleW", 227, reinterpret_cast<std::uintptr_t>(&tl_ReadConsoleW), ExportSupport::Full},
        {"WriteConsoleW", 228, reinterpret_cast<std::uintptr_t>(&tl_WriteConsoleW), ExportSupport::Full},
        {"IsDebuggerPresent", 229, reinterpret_cast<std::uintptr_t>(&tl_IsDebuggerPresent), ExportSupport::Full},
        {"IsProcessorFeaturePresent", 230,
         reinterpret_cast<std::uintptr_t>(&tl_IsProcessorFeaturePresent), ExportSupport::Full},
        {"EncodePointer", 231, reinterpret_cast<std::uintptr_t>(&tl_EncodePointer), ExportSupport::Full},
        {"DecodePointer", 232, reinterpret_cast<std::uintptr_t>(&tl_DecodePointer), ExportSupport::Full},
        {"InitializeSListHead", 233,
         reinterpret_cast<std::uintptr_t>(&tl_InitializeSListHead), ExportSupport::Full},
        {"FindFirstFileExW", 234, reinterpret_cast<std::uintptr_t>(&tl_FindFirstFileExW), ExportSupport::Full},
        {"SetFileAttributesW", 235, reinterpret_cast<std::uintptr_t>(&tl_SetFileAttributesW), ExportSupport::Full},
        {"SetFileInformationByHandle", 236,
         reinterpret_cast<std::uintptr_t>(&tl_SetFileInformationByHandle), ExportSupport::Full},
        {"InitializeCriticalSectionAndSpinCount", 239,
         reinterpret_cast<std::uintptr_t>(&tl_InitializeCriticalSectionAndSpinCount), ExportSupport::Full},
        {"InitializeCriticalSectionEx", 240,
         reinterpret_cast<std::uintptr_t>(&tl_InitializeCriticalSectionEx), ExportSupport::Full},
        {"GlobalAlloc", 241, reinterpret_cast<std::uintptr_t>(&tl_GlobalAlloc), ExportSupport::Full},
        {"GlobalLock", 242, reinterpret_cast<std::uintptr_t>(&tl_GlobalLock), ExportSupport::Full},
        {"GlobalUnlock", 243, reinterpret_cast<std::uintptr_t>(&tl_GlobalUnlock), ExportSupport::Full},
        {"GlobalFree", 244, reinterpret_cast<std::uintptr_t>(&tl_GlobalFree), ExportSupport::Full},
        {"LocalAlloc", 245, reinterpret_cast<std::uintptr_t>(&tl_LocalAlloc), ExportSupport::Full},
        {"LocalFree", 246, reinterpret_cast<std::uintptr_t>(&tl_LocalFree), ExportSupport::Full},
        {"OutputDebugStringA", 247, reinterpret_cast<std::uintptr_t>(&tl_OutputDebugStringA), ExportSupport::Full},
        {"OutputDebugStringW", 248, reinterpret_cast<std::uintptr_t>(&tl_OutputDebugStringW), ExportSupport::Full},
        {"SetDllDirectoryW", 249, reinterpret_cast<std::uintptr_t>(&tl_SetDllDirectoryW), ExportSupport::Full},
        {"VirtualQueryEx", 250, reinterpret_cast<std::uintptr_t>(&tl_VirtualQueryEx), ExportSupport::Full},
        {"GetTimeZoneInformation", 251,
         reinterpret_cast<std::uintptr_t>(&tl_GetTimeZoneInformation), ExportSupport::Full},
        {"GetProcessId", 252, reinterpret_cast<std::uintptr_t>(&tl_GetProcessId), ExportSupport::Full},
        {"QueryFullProcessImageNameW", 253,
         reinterpret_cast<std::uintptr_t>(&tl_QueryFullProcessImageNameW), ExportSupport::Full},
        {"FileTimeToLocalFileTime", 254,
         reinterpret_cast<std::uintptr_t>(&tl_FileTimeToLocalFileTime), ExportSupport::Full},
        {"GetLongPathNameW", 255, reinterpret_cast<std::uintptr_t>(&tl_GetLongPathNameW), ExportSupport::Full},
        {"GetShortPathNameW", 256, reinterpret_cast<std::uintptr_t>(&tl_GetShortPathNameW), ExportSupport::Full},
        {"SetThreadPriority", 257, reinterpret_cast<std::uintptr_t>(&tl_SetThreadPriority), ExportSupport::Full},
        {"GetProcessAffinityMask", 258,
         reinterpret_cast<std::uintptr_t>(&tl_GetProcessAffinityMask), ExportSupport::Full},
        {"CreateHardLinkW", 259, reinterpret_cast<std::uintptr_t>(&tl_CreateHardLinkW), ExportSupport::Full},
        {"K32GetModuleFileNameExW", 260, reinterpret_cast<std::uintptr_t>(&tl_K32GetModuleFileNameExW), ExportSupport::Full},
        {"GetTickCount", 261, reinterpret_cast<std::uintptr_t>(&tl_GetTickCount), ExportSupport::Full},
        {"SetCurrentDirectoryW", 262, reinterpret_cast<std::uintptr_t>(&tl_SetCurrentDirectoryW), ExportSupport::Full},
        {"DeviceIoControl", 263, reinterpret_cast<std::uintptr_t>(&tl_DeviceIoControl), ExportSupport::Full},
        {"FoldStringW", 264, reinterpret_cast<std::uintptr_t>(&tl_FoldStringW), ExportSupport::Full},
        {"SetThreadExecutionState", 265, reinterpret_cast<std::uintptr_t>(&tl_SetThreadExecutionState), ExportSupport::Full},
        {"AllocConsole", 266, reinterpret_cast<std::uintptr_t>(&tl_AllocConsole), ExportSupport::Full},
        {"AttachConsole", 267, reinterpret_cast<std::uintptr_t>(&tl_AttachConsole), ExportSupport::Full},
        {"FreeConsole", 268, reinterpret_cast<std::uintptr_t>(&tl_FreeConsole), ExportSupport::Full},
        {"SystemTimeToTzSpecificLocalTime", 269,
         reinterpret_cast<std::uintptr_t>(&tl_SystemTimeToTzSpecificLocalTime), ExportSupport::Full},
        {"IsDBCSLeadByte", 270, reinterpret_cast<std::uintptr_t>(&tl_IsDBCSLeadByte), ExportSupport::Full},
        {"GetNumberFormatW", 271, reinterpret_cast<std::uintptr_t>(&tl_GetNumberFormatW), ExportSupport::Full},
        {"GetVersion", 272, reinterpret_cast<std::uintptr_t>(&tl_GetVersion), ExportSupport::Full},
        {"GetLargePageMinimum", 273, reinterpret_cast<std::uintptr_t>(&tl_GetLargePageMinimum), ExportSupport::Full},
        {"SetFileApisToOEM", 274, reinterpret_cast<std::uintptr_t>(&tl_SetFileApisToOEM), ExportSupport::Full},
        {"SetConsoleCtrlHandler", 275, reinterpret_cast<std::uintptr_t>(&tl_SetConsoleCtrlHandler), ExportSupport::Full},
        {"GetProcessTimes", 276, reinterpret_cast<std::uintptr_t>(&tl_GetProcessTimes), ExportSupport::Full},
        {"SetProcessAffinityMask", 277, reinterpret_cast<std::uintptr_t>(&tl_SetProcessAffinityMask), ExportSupport::Full},
        {"SetThreadAffinityMask", 278, reinterpret_cast<std::uintptr_t>(&tl_SetThreadAffinityMask), ExportSupport::Full},
        {"ResumeThread", 279, reinterpret_cast<std::uintptr_t>(&tl_ResumeThread), ExportSupport::Full},
        {"OpenEventW", 280, reinterpret_cast<std::uintptr_t>(&tl_OpenEventW), ExportSupport::Full},
        {"OpenFileMappingW", 281, reinterpret_cast<std::uintptr_t>(&tl_OpenFileMappingW), ExportSupport::Full},
        {"FileTimeToDosDateTime", 282, reinterpret_cast<std::uintptr_t>(&tl_FileTimeToDosDateTime), ExportSupport::Full},
        {"CompareFileTime", 283, reinterpret_cast<std::uintptr_t>(&tl_CompareFileTime), ExportSupport::Full},
        {"GetDiskFreeSpaceW", 284, reinterpret_cast<std::uintptr_t>(&tl_GetDiskFreeSpaceW), ExportSupport::Full},
        {"FindFirstStreamW", 285, reinterpret_cast<std::uintptr_t>(&tl_FindFirstStreamW), ExportSupport::Full},
        {"FindNextStreamW", 286, reinterpret_cast<std::uintptr_t>(&tl_FindNextStreamW), ExportSupport::Full},
        {"GetLogicalDriveStringsW", 287, reinterpret_cast<std::uintptr_t>(&tl_GetLogicalDriveStringsW), ExportSupport::Full},
        {"SetNamedPipeHandleState", 288, reinterpret_cast<std::uintptr_t>(&tl_SetNamedPipeHandleState), ExportSupport::Full},
        {"TransactNamedPipe", 289, reinterpret_cast<std::uintptr_t>(&tl_TransactNamedPipe), ExportSupport::Full},
        {"WaitNamedPipeW", 290, reinterpret_cast<std::uintptr_t>(&tl_WaitNamedPipeW), ExportSupport::Full},
        {"PeekNamedPipe", 291, reinterpret_cast<std::uintptr_t>(&tl_PeekNamedPipe), ExportSupport::Full},
        {"WaitForSingleObjectEx", 292, reinterpret_cast<std::uintptr_t>(&tl_WaitForSingleObjectEx), ExportSupport::Full},
        {"GetExitCodeThread", 293, reinterpret_cast<std::uintptr_t>(&tl_GetExitCodeThread), ExportSupport::Full},
        {"TryAcquireSRWLockExclusive", 294, reinterpret_cast<std::uintptr_t>(&tl_TryAcquireSRWLockExclusive), ExportSupport::Full},
        {"FreeLibraryAndExitThread", 295, reinterpret_cast<std::uintptr_t>(&tl_FreeLibraryAndExitThread), ExportSupport::Full},
        {"SetThreadLocale", 296, reinterpret_cast<std::uintptr_t>(&tl_SetThreadLocale), ExportSupport::Full},
        {"SetThreadUILanguage", 297, reinterpret_cast<std::uintptr_t>(&tl_SetThreadUILanguage), ExportSupport::Full},
        {"GetUserDefaultUILanguage", 298, reinterpret_cast<std::uintptr_t>(&tl_GetUserDefaultUILanguage), ExportSupport::Full},
        {"GetLogicalDrives", 299, reinterpret_cast<std::uintptr_t>(&tl_GetLogicalDrives), ExportSupport::Full},
        {"GetPhysicallyInstalledSystemMemory", 300,
         reinterpret_cast<std::uintptr_t>(&tl_GetPhysicallyInstalledSystemMemory), ExportSupport::Full},
        {"GetVolumePathNameA", 301, reinterpret_cast<std::uintptr_t>(&tl_GetVolumePathNameA), ExportSupport::Full},
        {"TzSpecificLocalTimeToSystemTime", 302,
         reinterpret_cast<std::uintptr_t>(&tl_TzSpecificLocalTimeToSystemTime), ExportSupport::Full},
        {"UnregisterWaitEx", 303, reinterpret_cast<std::uintptr_t>(&tl_UnregisterWaitEx), ExportSupport::Full},
        {"RegisterWaitForSingleObject", 304,
         reinterpret_cast<std::uintptr_t>(&tl_RegisterWaitForSingleObject), ExportSupport::Full},
        {"SetSearchPathMode", 305, reinterpret_cast<std::uintptr_t>(&tl_SetSearchPathMode), ExportSupport::Full},
        {"InterlockedPushEntrySList", 306,
         reinterpret_cast<std::uintptr_t>(&tl_InterlockedPushEntrySList), ExportSupport::Full},
        {"CopyFileExW", 307, reinterpret_cast<std::uintptr_t>(&tl_CopyFileExW), ExportSupport::Full},
        {"MoveFileWithProgressW", 308, reinterpret_cast<std::uintptr_t>(&tl_MoveFileWithProgressW), ExportSupport::Full},
        {"GetCompressedFileSizeW", 309, reinterpret_cast<std::uintptr_t>(&tl_GetCompressedFileSizeW), ExportSupport::Full},
        {"FindFirstChangeNotificationW", 310,
         reinterpret_cast<std::uintptr_t>(&tl_FindFirstChangeNotificationW), ExportSupport::Full},
        {"FindNextChangeNotification", 311,
         reinterpret_cast<std::uintptr_t>(&tl_FindNextChangeNotification), ExportSupport::Full},
        {"FindCloseChangeNotification", 312,
         reinterpret_cast<std::uintptr_t>(&tl_FindCloseChangeNotification), ExportSupport::Full},
        {"GetSystemDefaultLangID", 313, reinterpret_cast<std::uintptr_t>(&tl_GetSystemDefaultLangID), ExportSupport::Full},
        {"GetUserDefaultLangID", 314, reinterpret_cast<std::uintptr_t>(&tl_GetUserDefaultLangID), ExportSupport::Full},
        {"GetWindowsDirectoryW", 315, reinterpret_cast<std::uintptr_t>(&tl_GetWindowsDirectoryW), ExportSupport::Full},
        {"GlobalSize", 316, reinterpret_cast<std::uintptr_t>(&tl_GlobalSize), ExportSupport::Full},
        {"SetPriorityClass", 317, reinterpret_cast<std::uintptr_t>(&tl_SetPriorityClass), ExportSupport::Full},
        {"lstrlenW", 318, reinterpret_cast<std::uintptr_t>(&tl_lstrlenW), ExportSupport::Full},
        {"K32GetProcessMemoryInfo", 319, reinterpret_cast<std::uintptr_t>(&tl_K32GetProcessMemoryInfo), ExportSupport::Full},
        {"K32GetProcessImageFileNameA", 320, reinterpret_cast<std::uintptr_t>(&tl_K32GetProcessImageFileNameA), ExportSupport::Full},
        {"Process32First", 321, reinterpret_cast<std::uintptr_t>(&tl_Process32First), ExportSupport::Full},
        {"Process32Next", 322, reinterpret_cast<std::uintptr_t>(&tl_Process32Next), ExportSupport::Full},
        {"DuplicateHandle", 323, reinterpret_cast<std::uintptr_t>(&tl_DuplicateHandle), ExportSupport::Full},
        {"LockFile", 324, reinterpret_cast<std::uintptr_t>(&tl_LockFile), ExportSupport::Full},
        {"LockFileEx", 325, reinterpret_cast<std::uintptr_t>(&tl_LockFileEx), ExportSupport::Full},
        {"UnlockFile", 326, reinterpret_cast<std::uintptr_t>(&tl_UnlockFile), ExportSupport::Full},
        {"UnlockFileEx", 327, reinterpret_cast<std::uintptr_t>(&tl_UnlockFileEx), ExportSupport::Full},
        {"GetDiskFreeSpaceA", 328, reinterpret_cast<std::uintptr_t>(&tl_GetDiskFreeSpaceA), ExportSupport::Full},
        {"GetTempPathA", 329, reinterpret_cast<std::uintptr_t>(&tl_GetTempPathA), ExportSupport::Full},
        {"MoveFileExA", 330, reinterpret_cast<std::uintptr_t>(&tl_MoveFileExA), ExportSupport::Full},
        {"SleepEx", 331, reinterpret_cast<std::uintptr_t>(&tl_SleepEx), ExportSupport::Full},
        {"WaitForMultipleObjectsEx", 332, reinterpret_cast<std::uintptr_t>(&tl_WaitForMultipleObjectsEx), ExportSupport::Full},
        {"TryEnterCriticalSection", 333, reinterpret_cast<std::uintptr_t>(&tl_TryEnterCriticalSection), ExportSupport::Full},
        {"InitializeConditionVariable", 334, reinterpret_cast<std::uintptr_t>(&tl_InitializeConditionVariable), ExportSupport::Full},
        {"SleepConditionVariableCS", 335, reinterpret_cast<std::uintptr_t>(&tl_SleepConditionVariableCS), ExportSupport::Full},
        {"FindResourceExW", 336, reinterpret_cast<std::uintptr_t>(&tl_FindResourceExW), ExportSupport::Full},
        {"CompareStringEx", 337, reinterpret_cast<std::uintptr_t>(&tl_CompareStringEx), ExportSupport::Full},
        {"CreateFile2", 338, reinterpret_cast<std::uintptr_t>(&tl_CreateFile2), ExportSupport::Full},
        {"GetCurrentProcessorNumber", 339, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentProcessorNumber), ExportSupport::Full},
        {"InitializeProcThreadAttributeList", 340, reinterpret_cast<std::uintptr_t>(&tl_InitializeProcThreadAttributeList), ExportSupport::Full},
        {"UpdateProcThreadAttribute", 341, reinterpret_cast<std::uintptr_t>(&tl_UpdateProcThreadAttribute), ExportSupport::Full},
        {"GetSystemDirectoryA", 342, reinterpret_cast<std::uintptr_t>(&tl_GetSystemDirectoryA), ExportSupport::Full},
        {"ReadConsoleA", 343, reinterpret_cast<std::uintptr_t>(&tl_ReadConsoleA), ExportSupport::Full},
        {"CreateWaitableTimerA", 344, reinterpret_cast<std::uintptr_t>(&tl_CreateWaitableTimerA), ExportSupport::Full},
        {"CreateWaitableTimerW", 345, reinterpret_cast<std::uintptr_t>(&tl_CreateWaitableTimerW), ExportSupport::Full},
        {"SetWaitableTimer", 346, reinterpret_cast<std::uintptr_t>(&tl_SetWaitableTimer), ExportSupport::Full},
        {"CancelWaitableTimer", 347, reinterpret_cast<std::uintptr_t>(&tl_CancelWaitableTimer), ExportSupport::Full},
        {"GetLogicalProcessorInformation", 348, reinterpret_cast<std::uintptr_t>(&tl_GetLogicalProcessorInformation), ExportSupport::Full},
        {"GetVolumePathNameW", 349, reinterpret_cast<std::uintptr_t>(&tl_GetVolumePathNameW), ExportSupport::Full},
        {"SetThreadDescription", 350, reinterpret_cast<std::uintptr_t>(&tl_SetThreadDescription), ExportSupport::Full},
        {"GetCurrentThread", 351, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentThread), ExportSupport::Full},
        {"CreateSemaphoreExW", 352, reinterpret_cast<std::uintptr_t>(&tl_CreateSemaphoreExW), ExportSupport::Full},
        {"OpenSemaphoreW", 353, reinterpret_cast<std::uintptr_t>(&tl_OpenSemaphoreW), ExportSupport::Full},
        {"CreateMutexExW", 354, reinterpret_cast<std::uintptr_t>(&tl_CreateMutexExW), ExportSupport::Full},
        {"DebugBreak", 355, reinterpret_cast<std::uintptr_t>(&tl_DebugBreak), ExportSupport::Full},
        {"InitOnceBeginInitialize", 356, reinterpret_cast<std::uintptr_t>(&tl_InitOnceBeginInitialize), ExportSupport::Full},
        {"InitOnceComplete", 357, reinterpret_cast<std::uintptr_t>(&tl_InitOnceComplete), ExportSupport::Full},
        {"SwitchToThread", 358, reinterpret_cast<std::uintptr_t>(&tl_SwitchToThread), ExportSupport::Full},
        {"GetSystemFirmwareTable", 359, reinterpret_cast<std::uintptr_t>(&tl_GetSystemFirmwareTable), ExportSupport::Full},
        {"__C_specific_handler", 360, reinterpret_cast<std::uintptr_t>(&tl___C_specific_handler), ExportSupport::Full},
        {"Beep", 361, reinterpret_cast<std::uintptr_t>(&tl_Beep), ExportSupport::Full},
        {"ClearCommBreak", 362, reinterpret_cast<std::uintptr_t>(&tl_ClearCommBreak), ExportSupport::Full},
        {"ConnectNamedPipe", 363, reinterpret_cast<std::uintptr_t>(&tl_ConnectNamedPipe), ExportSupport::Full},
        {"CreateNamedPipeA", 364, reinterpret_cast<std::uintptr_t>(&tl_CreateNamedPipeA), ExportSupport::Full},
        {"CreatePipe", 365, reinterpret_cast<std::uintptr_t>(&tl_CreatePipe), ExportSupport::Full},
        {"FindResourceA", 366, reinterpret_cast<std::uintptr_t>(&tl_FindResourceA), ExportSupport::Full},
        {"GetCommState", 367, reinterpret_cast<std::uintptr_t>(&tl_GetCommState), ExportSupport::Full},
        {"GetLocaleInfoA", 368, reinterpret_cast<std::uintptr_t>(&tl_GetLocaleInfoA), ExportSupport::Full},
        {"GetOverlappedResult", 369, reinterpret_cast<std::uintptr_t>(&tl_GetOverlappedResult), ExportSupport::Full},
        {"GetThreadTimes", 370, reinterpret_cast<std::uintptr_t>(&tl_GetThreadTimes), ExportSupport::Full},
        {"GetWindowsDirectoryA", 371, reinterpret_cast<std::uintptr_t>(&tl_GetWindowsDirectoryA), ExportSupport::Full},
        {"GlobalMemoryStatus", 372, reinterpret_cast<std::uintptr_t>(&tl_GlobalMemoryStatus), ExportSupport::Full},
        {"LocalFileTimeToFileTime", 373, reinterpret_cast<std::uintptr_t>(&tl_LocalFileTimeToFileTime), ExportSupport::Full},
        {"SetCommBreak", 374, reinterpret_cast<std::uintptr_t>(&tl_SetCommBreak), ExportSupport::Full},
        {"SetCommState", 375, reinterpret_cast<std::uintptr_t>(&tl_SetCommState), ExportSupport::Full},
        {"SetCommTimeouts", 376, reinterpret_cast<std::uintptr_t>(&tl_SetCommTimeouts), ExportSupport::Full},
        {"SetCurrentDirectoryA", 377, reinterpret_cast<std::uintptr_t>(&tl_SetCurrentDirectoryA), ExportSupport::Full},
        {"SetHandleInformation", 378, reinterpret_cast<std::uintptr_t>(&tl_SetHandleInformation), ExportSupport::Full},
        {"WaitNamedPipeA", 379, reinterpret_cast<std::uintptr_t>(&tl_WaitNamedPipeA), ExportSupport::Full},
        {"CreateProcessA", 380, reinterpret_cast<std::uintptr_t>(&tl_CreateProcessA), ExportSupport::Full},
        {"GetTimeFormatEx", 381, reinterpret_cast<std::uintptr_t>(&tl_GetTimeFormatEx), ExportSupport::Full},
        {"GetDateFormatEx", 382, reinterpret_cast<std::uintptr_t>(&tl_GetDateFormatEx), ExportSupport::Full},
        {"lstrcpynW", 383, reinterpret_cast<std::uintptr_t>(&tl_lstrcpynW), ExportSupport::Full},
        {"GetApplicationRestartSettings", 384, reinterpret_cast<std::uintptr_t>(&tl_GetApplicationRestartSettings), ExportSupport::Full},
        {"UnregisterApplicationRestart", 385, reinterpret_cast<std::uintptr_t>(&tl_UnregisterApplicationRestart), ExportSupport::Full},
        {"lstrcmpiA", 386, reinterpret_cast<std::uintptr_t>(&tl_lstrcmpiA), ExportSupport::Full},
        {"RegisterApplicationRestart", 387, reinterpret_cast<std::uintptr_t>(&tl_RegisterApplicationRestart), ExportSupport::Full},
        {"lstrcpynA", 388, reinterpret_cast<std::uintptr_t>(&tl_lstrcpynA), ExportSupport::Full},
        {"CancelIo", 389, reinterpret_cast<std::uintptr_t>(&tl_CancelIo), ExportSupport::Full},
        {"ReadDirectoryChangesW", 390, reinterpret_cast<std::uintptr_t>(&tl_ReadDirectoryChangesW), ExportSupport::Full},
        {"GetStringTypeExW", 391, reinterpret_cast<std::uintptr_t>(&tl_GetStringTypeExW), ExportSupport::Full},
        {"LCMapStringA", 392, reinterpret_cast<std::uintptr_t>(&tl_LCMapStringA), ExportSupport::Full},
        {"GetStringTypeExA", 393, reinterpret_cast<std::uintptr_t>(&tl_GetStringTypeExA), ExportSupport::Full},
        {"FreeLibraryWhenCallbackReturns", 394, reinterpret_cast<std::uintptr_t>(&tl_FreeLibraryWhenCallbackReturns), ExportSupport::Full},
        {"lstrcpyW", 395, reinterpret_cast<std::uintptr_t>(&tl_lstrcpyW), ExportSupport::Full},
        {"ReplaceFileW", 396, reinterpret_cast<std::uintptr_t>(&tl_ReplaceFileW), ExportSupport::Full},
        {"QueueUserAPC", 397, reinterpret_cast<std::uintptr_t>(&tl_QueueUserAPC), ExportSupport::Full},
        {"lstrcmpW", 398, reinterpret_cast<std::uintptr_t>(&tl_lstrcmpW), ExportSupport::Full},
        {"lstrcmpiW", 399, reinterpret_cast<std::uintptr_t>(&tl_lstrcmpiW), ExportSupport::Full},
        {"DosDateTimeToFileTime", 400, reinterpret_cast<std::uintptr_t>(&tl_DosDateTimeToFileTime), ExportSupport::Full},
        {"CreateRemoteThread", 401, reinterpret_cast<std::uintptr_t>(&tl_CreateRemoteThread), ExportSupport::Stub},
        {"VirtualAllocEx", 402, reinterpret_cast<std::uintptr_t>(&tl_VirtualAllocEx), ExportSupport::Full},
        {"VirtualFreeEx", 403, reinterpret_cast<std::uintptr_t>(&tl_VirtualFreeEx), ExportSupport::Full},
        {"WriteProcessMemory", 404, reinterpret_cast<std::uintptr_t>(&tl_WriteProcessMemory), ExportSupport::Stub},
        {"OpenFile", 405, reinterpret_cast<std::uintptr_t>(&tl_OpenFile), ExportSupport::Full},
        {"OpenEventA", 406, reinterpret_cast<std::uintptr_t>(&tl_OpenEventA), ExportSupport::Full},
        {"OpenFileMappingA", 407, reinterpret_cast<std::uintptr_t>(&tl_OpenFileMappingA), ExportSupport::Full},
        {"_lclose", 408, reinterpret_cast<std::uintptr_t>(&tl__lclose), ExportSupport::Full},
        {"FlushInstructionCache", 409, reinterpret_cast<std::uintptr_t>(&tl_FlushInstructionCache), ExportSupport::Full},
        {"SetThreadContext", 410, reinterpret_cast<std::uintptr_t>(&tl_SetThreadContext), ExportSupport::Full},
        {"GetThreadContext", 411, reinterpret_cast<std::uintptr_t>(&tl_GetThreadContext), ExportSupport::Full},
        {"SuspendThread", 412, reinterpret_cast<std::uintptr_t>(&tl_SuspendThread), ExportSupport::Full},
        {"VirtualProtectEx", 413, reinterpret_cast<std::uintptr_t>(&tl_VirtualProtectEx), ExportSupport::Full},
        {"lstrcmpA", 414, reinterpret_cast<std::uintptr_t>(&tl_lstrcmpA), ExportSupport::Full},
        {"IsThreadAFiber", 415, reinterpret_cast<std::uintptr_t>(&tl_IsThreadAFiber), ExportSupport::Full},
        {"InterlockedFlushSList", 416, reinterpret_cast<std::uintptr_t>(&tl_InterlockedFlushSList), ExportSupport::Full},
        {"lstrcatW", 417, reinterpret_cast<std::uintptr_t>(&tl_lstrcatW), ExportSupport::Full},
        {"SetDefaultDllDirectories", 418, reinterpret_cast<std::uintptr_t>(&tl_SetDefaultDllDirectories), ExportSupport::Full},
    };
    static const InternalModule kKernel32Module{"KERNEL32.dll", kKernel32Exports};
    register_module(kKernel32Module);
}

}  // namespace tradutorlinux::loader
