#include "kernel32_internal.hpp"

namespace tradutorlinux::loader {

void register_kernel32_module() {
    static const ExportedFunction kKernel32Exports[] = {
        {"GetStdHandle", 1, reinterpret_cast<std::uintptr_t>(&tl_GetStdHandle)},
        {"WriteFile", 2, reinterpret_cast<std::uintptr_t>(&tl_WriteFile)},
        {"ReadFile", 3, reinterpret_cast<std::uintptr_t>(&tl_ReadFile)},
        {"ExitProcess", 4, reinterpret_cast<std::uintptr_t>(&tl_ExitProcess)},
        {"GetLastError", 5, reinterpret_cast<std::uintptr_t>(&tl_GetLastError)},
        {"SetLastError", 6, reinterpret_cast<std::uintptr_t>(&tl_SetLastError)},
        {"VirtualAlloc", 7, reinterpret_cast<std::uintptr_t>(&tl_VirtualAlloc)},
        {"VirtualFree", 8, reinterpret_cast<std::uintptr_t>(&tl_VirtualFree)},
        {"CreateFileA", 9, reinterpret_cast<std::uintptr_t>(&tl_CreateFileA)},
        {"CreateFileW", 69, reinterpret_cast<std::uintptr_t>(&tl_CreateFileW)},
        {"CloseHandle", 10, reinterpret_cast<std::uintptr_t>(&tl_CloseHandle)},
        {"DeleteCriticalSection", 11, reinterpret_cast<std::uintptr_t>(&tl_DeleteCriticalSection)},
        {"EnterCriticalSection", 12, reinterpret_cast<std::uintptr_t>(&tl_EnterCriticalSection)},
        {"GetConsoleMode", 13, reinterpret_cast<std::uintptr_t>(&tl_GetConsoleMode)},
        {"InitializeCriticalSection", 14, reinterpret_cast<std::uintptr_t>(&tl_InitializeCriticalSection)},
        {"IsDBCSLeadByteEx", 15, reinterpret_cast<std::uintptr_t>(&tl_IsDBCSLeadByteEx)},
        {"LeaveCriticalSection", 16, reinterpret_cast<std::uintptr_t>(&tl_LeaveCriticalSection)},
        {"MultiByteToWideChar", 17, reinterpret_cast<std::uintptr_t>(&tl_MultiByteToWideChar)},
        {"SetConsoleMode", 18, reinterpret_cast<std::uintptr_t>(&tl_SetConsoleMode)},
        {"SetUnhandledExceptionFilter", 19, reinterpret_cast<std::uintptr_t>(&tl_SetUnhandledExceptionFilter)},
        {"Sleep", 20, reinterpret_cast<std::uintptr_t>(&tl_Sleep)},
        {"TlsGetValue", 21, reinterpret_cast<std::uintptr_t>(&tl_TlsGetValue)},
        {"VirtualProtect", 22, reinterpret_cast<std::uintptr_t>(&tl_VirtualProtect)},
        {"VirtualQuery", 23, reinterpret_cast<std::uintptr_t>(&tl_VirtualQuery)},
        {"WideCharToMultiByte", 24, reinterpret_cast<std::uintptr_t>(&tl_WideCharToMultiByte)},
        {"GetModuleHandleA", 25, reinterpret_cast<std::uintptr_t>(&tl_GetModuleHandleA)},
        {"GetModuleHandleW", 26, reinterpret_cast<std::uintptr_t>(&tl_GetModuleHandleW)},
        {"GetProcAddress", 27, reinterpret_cast<std::uintptr_t>(&tl_GetProcAddress)},
        {"GetCommandLineA", 28, reinterpret_cast<std::uintptr_t>(&tl_GetCommandLineA)},
        {"GetCommandLineW", 29, reinterpret_cast<std::uintptr_t>(&tl_GetCommandLineW)},
        {"GetEnvironmentVariableA", 30, reinterpret_cast<std::uintptr_t>(&tl_GetEnvironmentVariableA)},
        {"GetEnvironmentVariableW", 31, reinterpret_cast<std::uintptr_t>(&tl_GetEnvironmentVariableW)},
        {"GetProcessHeap", 32, reinterpret_cast<std::uintptr_t>(&tl_GetProcessHeap)},
        {"HeapAlloc", 33, reinterpret_cast<std::uintptr_t>(&tl_HeapAlloc)},
        {"HeapFree", 34, reinterpret_cast<std::uintptr_t>(&tl_HeapFree)},
        {"HeapReAlloc", 35, reinterpret_cast<std::uintptr_t>(&tl_HeapReAlloc)},
        {"GetTickCount64", 36, reinterpret_cast<std::uintptr_t>(&tl_GetTickCount64)},
        {"GetSystemTimeAsFileTime", 37, reinterpret_cast<std::uintptr_t>(&tl_GetSystemTimeAsFileTime)},
        {"GetFileSize", 38, reinterpret_cast<std::uintptr_t>(&tl_GetFileSize)},
        {"SetFilePointer", 39, reinterpret_cast<std::uintptr_t>(&tl_SetFilePointer)},
        {"GetFileAttributesA", 40, reinterpret_cast<std::uintptr_t>(&tl_GetFileAttributesA)},
        {"DeleteFileA", 41, reinterpret_cast<std::uintptr_t>(&tl_DeleteFileA)},
        {"MoveFileA", 42, reinterpret_cast<std::uintptr_t>(&tl_MoveFileA)},
        {"CreateDirectoryA", 43, reinterpret_cast<std::uintptr_t>(&tl_CreateDirectoryA)},
        {"FindFirstFileA", 44, reinterpret_cast<std::uintptr_t>(&tl_FindFirstFileA)},
        {"FindNextFileA", 45, reinterpret_cast<std::uintptr_t>(&tl_FindNextFileA)},
        {"FindClose", 46, reinterpret_cast<std::uintptr_t>(&tl_FindClose)},
        {"GetCurrentDirectoryA", 47, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentDirectoryA)},
        {"GetCurrentDirectoryW", 48, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentDirectoryW)},
        {"GetModuleFileNameA", 49, reinterpret_cast<std::uintptr_t>(&tl_GetModuleFileNameA)},
        {"GetModuleFileNameW", 193, reinterpret_cast<std::uintptr_t>(&tl_GetModuleFileNameW)},
        // Fase 11: ConcorrÃªncia.
        {"TlsAlloc", 50, reinterpret_cast<std::uintptr_t>(&tl_TlsAlloc)},
        {"TlsSetValue", 51, reinterpret_cast<std::uintptr_t>(&tl_TlsSetValue)},
        {"TlsFree", 52, reinterpret_cast<std::uintptr_t>(&tl_TlsFree)},
        {"CreateThread", 53, reinterpret_cast<std::uintptr_t>(&tl_CreateThread)},
        {"ExitThread", 54, reinterpret_cast<std::uintptr_t>(&tl_ExitThread)},
        {"WaitForSingleObject", 55, reinterpret_cast<std::uintptr_t>(&tl_WaitForSingleObject)},
        {"GetCurrentThreadId", 56, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentThreadId)},
        {"GetCurrentProcessId", 57, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentProcessId)},
        // Fase 10+: variantes wide do sistema de arquivos e console.
        {"GetFileAttributesW", 58, reinterpret_cast<std::uintptr_t>(&tl_GetFileAttributesW)},
        {"FindFirstFileW", 59, reinterpret_cast<std::uintptr_t>(&tl_FindFirstFileW)},
        {"FindNextFileW", 60, reinterpret_cast<std::uintptr_t>(&tl_FindNextFileW)},
        {"FormatMessageW", 61, reinterpret_cast<std::uintptr_t>(&tl_FormatMessageW)},
        {"FormatMessageA", 237, reinterpret_cast<std::uintptr_t>(&tl_FormatMessageA)},
        {"AreFileApisANSI", 238, reinterpret_cast<std::uintptr_t>(&tl_AreFileApisANSI)},
        {"GetConsoleOutputCP", 62, reinterpret_cast<std::uintptr_t>(&tl_GetConsoleOutputCP)},
        {"GetTempFileNameW", 63, reinterpret_cast<std::uintptr_t>(&tl_GetTempFileNameW)},
        {"LocalFree", 64, reinterpret_cast<std::uintptr_t>(&tl_LocalFree)},
        {"SetConsoleOutputCP", 65, reinterpret_cast<std::uintptr_t>(&tl_SetConsoleOutputCP)},
        {"CreateMutexA", 66, reinterpret_cast<std::uintptr_t>(&tl_CreateMutexA)},
        {"GetStartupInfoA", 67, reinterpret_cast<std::uintptr_t>(&tl_GetStartupInfoA)},
        {"MulDiv", 68, reinterpret_cast<std::uintptr_t>(&tl_MulDiv)},
        {"GetFileSizeEx", 70, reinterpret_cast<std::uintptr_t>(&tl_GetFileSizeEx)},
        {"SetFilePointerEx", 71, reinterpret_cast<std::uintptr_t>(&tl_SetFilePointerEx)},
        {"SetEndOfFile", 72, reinterpret_cast<std::uintptr_t>(&tl_SetEndOfFile)},
        {"FlushFileBuffers", 73, reinterpret_cast<std::uintptr_t>(&tl_FlushFileBuffers)},
        {"GetFileAttributesExW", 74, reinterpret_cast<std::uintptr_t>(&tl_GetFileAttributesExW)},
        {"DeleteFileW", 75, reinterpret_cast<std::uintptr_t>(&tl_DeleteFileW)},
        {"MoveFileW", 76, reinterpret_cast<std::uintptr_t>(&tl_MoveFileW)},
        {"MoveFileExW", 77, reinterpret_cast<std::uintptr_t>(&tl_MoveFileExW)},
        {"CopyFileW", 78, reinterpret_cast<std::uintptr_t>(&tl_CopyFileW)},
        {"CreateDirectoryW", 79, reinterpret_cast<std::uintptr_t>(&tl_CreateDirectoryW)},
        {"RemoveDirectoryW", 80, reinterpret_cast<std::uintptr_t>(&tl_RemoveDirectoryW)},
        {"GetTempPathW", 81, reinterpret_cast<std::uintptr_t>(&tl_GetTempPathW)},
        {"GetFullPathNameW", 82, reinterpret_cast<std::uintptr_t>(&tl_GetFullPathNameW)},
        {"GetFullPathNameA", 171, reinterpret_cast<std::uintptr_t>(&tl_GetFullPathNameA)},
        {"GetFileTime", 83, reinterpret_cast<std::uintptr_t>(&tl_GetFileTime)},
        {"SetFileTime", 84, reinterpret_cast<std::uintptr_t>(&tl_SetFileTime)},
        {"GetFileInformationByHandle", 85,
         reinterpret_cast<std::uintptr_t>(&tl_GetFileInformationByHandle)},
        {"GetFileInformationByHandleEx", 86,
         reinterpret_cast<std::uintptr_t>(&tl_GetFileInformationByHandleEx)},
        {"GetFinalPathNameByHandleW", 87,
         reinterpret_cast<std::uintptr_t>(&tl_GetFinalPathNameByHandleW)},
        {"FindResourceW", 88, reinterpret_cast<std::uintptr_t>(&tl_FindResourceW)},
        {"LoadResource", 89, reinterpret_cast<std::uintptr_t>(&tl_LoadResource)},
        {"LockResource", 90, reinterpret_cast<std::uintptr_t>(&tl_LockResource)},
        {"SizeofResource", 91, reinterpret_cast<std::uintptr_t>(&tl_SizeofResource)},
        {"CreateMutexW", 92, reinterpret_cast<std::uintptr_t>(&tl_CreateMutexW)},
        {"CreateEventA", 93, reinterpret_cast<std::uintptr_t>(&tl_CreateEventA)},
        {"CreateEventW", 94, reinterpret_cast<std::uintptr_t>(&tl_CreateEventW)},
        {"SetEvent", 95, reinterpret_cast<std::uintptr_t>(&tl_SetEvent)},
        {"ResetEvent", 96, reinterpret_cast<std::uintptr_t>(&tl_ResetEvent)},
        {"ReleaseMutex", 101, reinterpret_cast<std::uintptr_t>(&tl_ReleaseMutex)},
        {"CreateProcessW", 102, reinterpret_cast<std::uintptr_t>(&tl_CreateProcessW)},
        {"GetExitCodeProcess", 103,
         reinterpret_cast<std::uintptr_t>(&tl_GetExitCodeProcess)},
        {"TerminateProcess", 104, reinterpret_cast<std::uintptr_t>(&tl_TerminateProcess)},
        {"CreateSemaphoreA", 97, reinterpret_cast<std::uintptr_t>(&tl_CreateSemaphoreA)},
        {"CreateSemaphoreW", 98, reinterpret_cast<std::uintptr_t>(&tl_CreateSemaphoreW)},
        {"ReleaseSemaphore", 99, reinterpret_cast<std::uintptr_t>(&tl_ReleaseSemaphore)},
        {"WaitForMultipleObjects", 100,
         reinterpret_cast<std::uintptr_t>(&tl_WaitForMultipleObjects)},
        {"QueryPerformanceCounter", 105, reinterpret_cast<std::uintptr_t>(&tl_QueryPerformanceCounter)},
        {"QueryPerformanceFrequency", 106, reinterpret_cast<std::uintptr_t>(&tl_QueryPerformanceFrequency)},
        {"GetSystemInfo", 107, reinterpret_cast<std::uintptr_t>(&tl_GetSystemInfo)},
        {"GetNativeSystemInfo", 108, reinterpret_cast<std::uintptr_t>(&tl_GetNativeSystemInfo)},
        {"GlobalMemoryStatusEx", 109, reinterpret_cast<std::uintptr_t>(&tl_GlobalMemoryStatusEx)},
        {"CreateFileMappingA", 110, reinterpret_cast<std::uintptr_t>(&tl_CreateFileMappingA)},
        {"CreateFileMappingW", 111, reinterpret_cast<std::uintptr_t>(&tl_CreateFileMappingW)},
        {"MapViewOfFile", 112, reinterpret_cast<std::uintptr_t>(&tl_MapViewOfFile)},
        {"UnmapViewOfFile", 113, reinterpret_cast<std::uintptr_t>(&tl_UnmapViewOfFile)},
        {"FlushViewOfFile", 114, reinterpret_cast<std::uintptr_t>(&tl_FlushViewOfFile)},
        {"GetDiskFreeSpaceExA", 115, reinterpret_cast<std::uintptr_t>(&tl_GetDiskFreeSpaceExA)},
        {"GetDiskFreeSpaceExW", 116, reinterpret_cast<std::uintptr_t>(&tl_GetDiskFreeSpaceExW)},
        {"GetDriveTypeA", 117, reinterpret_cast<std::uintptr_t>(&tl_GetDriveTypeA)},
        {"GetDriveTypeW", 118, reinterpret_cast<std::uintptr_t>(&tl_GetDriveTypeW)},
        {"GetVolumeInformationA", 119, reinterpret_cast<std::uintptr_t>(&tl_GetVolumeInformationA)},
        {"GetVolumeInformationW", 120, reinterpret_cast<std::uintptr_t>(&tl_GetVolumeInformationW)},
        {"GetSystemTime", 121, reinterpret_cast<std::uintptr_t>(&tl_GetSystemTime)},
        {"GetLocalTime", 122, reinterpret_cast<std::uintptr_t>(&tl_GetLocalTime)},
        {"FileTimeToSystemTime", 123, reinterpret_cast<std::uintptr_t>(&tl_FileTimeToSystemTime)},
        {"SystemTimeToFileTime", 124, reinterpret_cast<std::uintptr_t>(&tl_SystemTimeToFileTime)},
        {"CompareStringA", 125, reinterpret_cast<std::uintptr_t>(&tl_CompareStringA)},
        {"CompareStringW", 126, reinterpret_cast<std::uintptr_t>(&tl_CompareStringW)},
        {"GetUserDefaultLCID", 127, reinterpret_cast<std::uintptr_t>(&tl_GetUserDefaultLCID)},
        {"GetSystemDefaultLCID", 128, reinterpret_cast<std::uintptr_t>(&tl_GetSystemDefaultLCID)},
        {"GetComputerNameA", 129, reinterpret_cast<std::uintptr_t>(&tl_GetComputerNameA)},
        {"GetComputerNameW", 130, reinterpret_cast<std::uintptr_t>(&tl_GetComputerNameW)},
        {"InitializeSRWLock", 131, reinterpret_cast<std::uintptr_t>(&tl_InitializeSRWLock)},
        {"AcquireSRWLockExclusive", 132, reinterpret_cast<std::uintptr_t>(&tl_AcquireSRWLockExclusive)},
        {"ReleaseSRWLockExclusive", 133, reinterpret_cast<std::uintptr_t>(&tl_ReleaseSRWLockExclusive)},
        {"AcquireSRWLockShared", 134, reinterpret_cast<std::uintptr_t>(&tl_AcquireSRWLockShared)},
        {"ReleaseSRWLockShared", 135, reinterpret_cast<std::uintptr_t>(&tl_ReleaseSRWLockShared)},
        {"SleepConditionVariableSRW", 136, reinterpret_cast<std::uintptr_t>(&tl_SleepConditionVariableSRW)},
        {"WakeConditionVariable", 137, reinterpret_cast<std::uintptr_t>(&tl_WakeConditionVariable)},
        {"WakeAllConditionVariable", 138, reinterpret_cast<std::uintptr_t>(&tl_WakeAllConditionVariable)},
        {"AddVectoredExceptionHandler", 139, reinterpret_cast<std::uintptr_t>(&tl_AddVectoredExceptionHandler)},
        {"RemoveVectoredExceptionHandler", 140, reinterpret_cast<std::uintptr_t>(&tl_RemoveVectoredExceptionHandler)},
        {"RaiseException", 141, reinterpret_cast<std::uintptr_t>(&tl_RaiseException)},
        {"GetPrivateProfileStringA", 142, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileStringA)},
        {"GetPrivateProfileStringW", 143, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileStringW)},
        {"GetPrivateProfileIntA", 144, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileIntA)},
        {"GetPrivateProfileIntW", 145, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileIntW)},
        {"WritePrivateProfileStringA", 146, reinterpret_cast<std::uintptr_t>(&tl_WritePrivateProfileStringA)},
        {"WritePrivateProfileStringW", 147, reinterpret_cast<std::uintptr_t>(&tl_WritePrivateProfileStringW)},
        {"GetPrivateProfileSectionA", 148, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileSectionA)},
        {"GetPrivateProfileSectionW", 149, reinterpret_cast<std::uintptr_t>(&tl_GetPrivateProfileSectionW)},
        {"GetConsoleScreenBufferInfo", 150, reinterpret_cast<std::uintptr_t>(&tl_GetConsoleScreenBufferInfo)},
        {"SetConsoleTextAttribute", 151, reinterpret_cast<std::uintptr_t>(&tl_SetConsoleTextAttribute)},
        {"CreateThreadpoolWork", 152, reinterpret_cast<std::uintptr_t>(&tl_CreateThreadpoolWork)},
        {"SubmitThreadpoolWork", 153, reinterpret_cast<std::uintptr_t>(&tl_SubmitThreadpoolWork)},
        {"WaitForThreadpoolWorkCallbacks", 154, reinterpret_cast<std::uintptr_t>(&tl_WaitForThreadpoolWorkCallbacks)},
        {"CloseThreadpoolWork", 155, reinterpret_cast<std::uintptr_t>(&tl_CloseThreadpoolWork)},
        {"CreateThreadpoolTimer", 156, reinterpret_cast<std::uintptr_t>(&tl_CreateThreadpoolTimer)},
        {"SetThreadpoolTimer", 157, reinterpret_cast<std::uintptr_t>(&tl_SetThreadpoolTimer)},
        {"WaitForThreadpoolTimerCallbacks", 158, reinterpret_cast<std::uintptr_t>(&tl_WaitForThreadpoolTimerCallbacks)},
        {"CloseThreadpoolTimer", 159, reinterpret_cast<std::uintptr_t>(&tl_CloseThreadpoolTimer)},
        {"ConvertThreadToFiber", 160, reinterpret_cast<std::uintptr_t>(&tl_ConvertThreadToFiber)},
        {"ConvertThreadToFiberEx", 188, reinterpret_cast<std::uintptr_t>(&tl_ConvertThreadToFiberEx)},
        {"ConvertFiberToThread", 161, reinterpret_cast<std::uintptr_t>(&tl_ConvertFiberToThread)},
        {"CreateFiber", 162, reinterpret_cast<std::uintptr_t>(&tl_CreateFiber)},
        {"CreateFiberEx", 189, reinterpret_cast<std::uintptr_t>(&tl_CreateFiberEx)},
        {"SwitchToFiber", 163, reinterpret_cast<std::uintptr_t>(&tl_SwitchToFiber)},
        {"DeleteFiber", 164, reinterpret_cast<std::uintptr_t>(&tl_DeleteFiber)},
        {"GetFiberData", 165, reinterpret_cast<std::uintptr_t>(&tl_GetFiberData)},
        {"CreateToolhelp32Snapshot", 190, reinterpret_cast<std::uintptr_t>(&tl_CreateToolhelp32Snapshot)},
        {"Process32FirstW", 191, reinterpret_cast<std::uintptr_t>(&tl_Process32FirstW)},
        {"Process32NextW", 192, reinterpret_cast<std::uintptr_t>(&tl_Process32NextW)},
        {"OpenProcess", 193, reinterpret_cast<std::uintptr_t>(&tl_OpenProcess)},
        {"HeapCreate", 166, reinterpret_cast<std::uintptr_t>(&tl_HeapCreate)},
        {"HeapDestroy", 167, reinterpret_cast<std::uintptr_t>(&tl_HeapDestroy)},
        {"HeapValidate", 168, reinterpret_cast<std::uintptr_t>(&tl_HeapValidate)},
        {"HeapSize", 169, reinterpret_cast<std::uintptr_t>(&tl_HeapSize)},
        {"HeapCompact", 170, reinterpret_cast<std::uintptr_t>(&tl_HeapCompact)},
        {"LoadLibraryA", 172, reinterpret_cast<std::uintptr_t>(&tl_LoadLibraryA)},
        {"LoadLibraryW", 173, reinterpret_cast<std::uintptr_t>(&tl_LoadLibraryW)},
        {"LoadLibraryExA", 174, reinterpret_cast<std::uintptr_t>(&tl_LoadLibraryExA)},
        {"LoadLibraryExW", 175, reinterpret_cast<std::uintptr_t>(&tl_LoadLibraryExW)},
        {"FreeLibrary", 176, reinterpret_cast<std::uintptr_t>(&tl_FreeLibrary)},
        {"GetModuleHandleExA", 177, reinterpret_cast<std::uintptr_t>(&tl_GetModuleHandleExA)},
        {"GetModuleHandleExW", 178, reinterpret_cast<std::uintptr_t>(&tl_GetModuleHandleExW)},
        {"GetVersionExA", 179, reinterpret_cast<std::uintptr_t>(&tl_GetVersionExA)},
        {"GetVersionExW", 180, reinterpret_cast<std::uintptr_t>(&tl_GetVersionExW)},
        {"VerifyVersionInfoW", 181, reinterpret_cast<std::uintptr_t>(&tl_VerifyVersionInfoW)},
        {"VerSetConditionMask", 182, reinterpret_cast<std::uintptr_t>(&tl_VerSetConditionMask)},
        {"GetUserDefaultLocaleName", 183, reinterpret_cast<std::uintptr_t>(&tl_GetUserDefaultLocaleName)},
        {"LocaleNameToLCID", 184, reinterpret_cast<std::uintptr_t>(&tl_LocaleNameToLCID)},
        {"WaitOnAddress", 185, reinterpret_cast<std::uintptr_t>(&tl_WaitOnAddress)},
        {"WakeByAddressSingle", 186, reinterpret_cast<std::uintptr_t>(&tl_WakeByAddressSingle)},
        {"WakeByAddressAll", 187, reinterpret_cast<std::uintptr_t>(&tl_WakeByAddressAll)},
        {"GetCurrentProcess", 194, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentProcess)},
        {"RtlCaptureContext", 195, reinterpret_cast<std::uintptr_t>(&tl_RtlCaptureContext)},
        {"RtlLookupFunctionEntry", 196, reinterpret_cast<std::uintptr_t>(&tl_RtlLookupFunctionEntry)},
        {"RtlVirtualUnwind", 197, reinterpret_cast<std::uintptr_t>(&tl_RtlVirtualUnwind)},
        {"RtlPcToFileHeader", 198, reinterpret_cast<std::uintptr_t>(&tl_RtlPcToFileHeader)},
        {"RtlUnwind", 199, reinterpret_cast<std::uintptr_t>(&tl_RtlUnwind)},
        {"RtlUnwindEx", 200, reinterpret_cast<std::uintptr_t>(&tl_RtlUnwindEx)},
        {"UnhandledExceptionFilter", 201, reinterpret_cast<std::uintptr_t>(&tl_UnhandledExceptionFilter)},
        {"SetEnvironmentVariableW", 202, reinterpret_cast<std::uintptr_t>(&tl_SetEnvironmentVariableW)},
        {"GetEnvironmentStringsW", 203, reinterpret_cast<std::uintptr_t>(&tl_GetEnvironmentStringsW)},
        {"FreeEnvironmentStringsW", 204, reinterpret_cast<std::uintptr_t>(&tl_FreeEnvironmentStringsW)},
        {"ExpandEnvironmentStringsW", 205, reinterpret_cast<std::uintptr_t>(&tl_ExpandEnvironmentStringsW)},
        {"FlsAlloc", 206, reinterpret_cast<std::uintptr_t>(&tl_FlsAlloc)},
        {"FlsFree", 207, reinterpret_cast<std::uintptr_t>(&tl_FlsFree)},
        {"FlsGetValue", 208, reinterpret_cast<std::uintptr_t>(&tl_FlsGetValue)},
        {"FlsSetValue", 209, reinterpret_cast<std::uintptr_t>(&tl_FlsSetValue)},
        {"GetACP", 210, reinterpret_cast<std::uintptr_t>(&tl_GetACP)},
        {"GetOEMCP", 211, reinterpret_cast<std::uintptr_t>(&tl_GetOEMCP)},
        {"GetCPInfo", 212, reinterpret_cast<std::uintptr_t>(&tl_GetCPInfo)},
        {"GetLocaleInfoW", 213, reinterpret_cast<std::uintptr_t>(&tl_GetLocaleInfoW)},
        {"LCMapStringW", 214, reinterpret_cast<std::uintptr_t>(&tl_LCMapStringW)},
        {"LCMapStringEx", 215, reinterpret_cast<std::uintptr_t>(&tl_LCMapStringEx)},
        {"GetLocaleInfoEx", 216, reinterpret_cast<std::uintptr_t>(&tl_GetLocaleInfoEx)},
        {"IsValidLocale", 217, reinterpret_cast<std::uintptr_t>(&tl_IsValidLocale)},
        {"IsValidCodePage", 218, reinterpret_cast<std::uintptr_t>(&tl_IsValidCodePage)},
        {"EnumSystemLocalesW", 219, reinterpret_cast<std::uintptr_t>(&tl_EnumSystemLocalesW)},
        {"GetStringTypeW", 220, reinterpret_cast<std::uintptr_t>(&tl_GetStringTypeW)},
        {"GetDateFormatW", 221, reinterpret_cast<std::uintptr_t>(&tl_GetDateFormatW)},
        {"GetTimeFormatW", 222, reinterpret_cast<std::uintptr_t>(&tl_GetTimeFormatW)},
        {"GetStartupInfoW", 223, reinterpret_cast<std::uintptr_t>(&tl_GetStartupInfoW)},
        {"GetSystemDirectoryW", 224, reinterpret_cast<std::uintptr_t>(&tl_GetSystemDirectoryW)},
        {"GetFileType", 225, reinterpret_cast<std::uintptr_t>(&tl_GetFileType)},
        {"SetStdHandle", 226, reinterpret_cast<std::uintptr_t>(&tl_SetStdHandle)},
        {"ReadConsoleW", 227, reinterpret_cast<std::uintptr_t>(&tl_ReadConsoleW)},
        {"WriteConsoleW", 228, reinterpret_cast<std::uintptr_t>(&tl_WriteConsoleW)},
        {"IsDebuggerPresent", 229, reinterpret_cast<std::uintptr_t>(&tl_IsDebuggerPresent)},
        {"IsProcessorFeaturePresent", 230,
         reinterpret_cast<std::uintptr_t>(&tl_IsProcessorFeaturePresent)},
        {"EncodePointer", 231, reinterpret_cast<std::uintptr_t>(&tl_EncodePointer)},
        {"DecodePointer", 232, reinterpret_cast<std::uintptr_t>(&tl_DecodePointer)},
        {"InitializeSListHead", 233,
         reinterpret_cast<std::uintptr_t>(&tl_InitializeSListHead)},
        {"FindFirstFileExW", 234, reinterpret_cast<std::uintptr_t>(&tl_FindFirstFileExW)},
        {"SetFileAttributesW", 235, reinterpret_cast<std::uintptr_t>(&tl_SetFileAttributesW)},
        {"SetFileInformationByHandle", 236,
         reinterpret_cast<std::uintptr_t>(&tl_SetFileInformationByHandle)},
        {"InitializeCriticalSectionAndSpinCount", 239,
         reinterpret_cast<std::uintptr_t>(&tl_InitializeCriticalSectionAndSpinCount)},
        {"InitializeCriticalSectionEx", 240,
         reinterpret_cast<std::uintptr_t>(&tl_InitializeCriticalSectionEx)},
        {"GlobalAlloc", 241, reinterpret_cast<std::uintptr_t>(&tl_GlobalAlloc)},
        {"GlobalLock", 242, reinterpret_cast<std::uintptr_t>(&tl_GlobalLock)},
        {"GlobalUnlock", 243, reinterpret_cast<std::uintptr_t>(&tl_GlobalUnlock)},
        {"GlobalFree", 244, reinterpret_cast<std::uintptr_t>(&tl_GlobalFree)},
        {"LocalAlloc", 245, reinterpret_cast<std::uintptr_t>(&tl_LocalAlloc)},
        {"LocalFree", 246, reinterpret_cast<std::uintptr_t>(&tl_LocalFree)},
        {"OutputDebugStringA", 247, reinterpret_cast<std::uintptr_t>(&tl_OutputDebugStringA)},
        {"OutputDebugStringW", 248, reinterpret_cast<std::uintptr_t>(&tl_OutputDebugStringW)},
        {"SetDllDirectoryW", 249, reinterpret_cast<std::uintptr_t>(&tl_SetDllDirectoryW)},
        {"VirtualQueryEx", 250, reinterpret_cast<std::uintptr_t>(&tl_VirtualQueryEx)},
        {"GetTimeZoneInformation", 251,
         reinterpret_cast<std::uintptr_t>(&tl_GetTimeZoneInformation)},
        {"GetProcessId", 252, reinterpret_cast<std::uintptr_t>(&tl_GetProcessId)},
        {"QueryFullProcessImageNameW", 253,
         reinterpret_cast<std::uintptr_t>(&tl_QueryFullProcessImageNameW)},
        {"FileTimeToLocalFileTime", 254,
         reinterpret_cast<std::uintptr_t>(&tl_FileTimeToLocalFileTime)},
        {"GetLongPathNameW", 255, reinterpret_cast<std::uintptr_t>(&tl_GetLongPathNameW)},
        {"GetShortPathNameW", 256, reinterpret_cast<std::uintptr_t>(&tl_GetShortPathNameW)},
        {"SetThreadPriority", 257, reinterpret_cast<std::uintptr_t>(&tl_SetThreadPriority)},
        {"GetProcessAffinityMask", 258,
         reinterpret_cast<std::uintptr_t>(&tl_GetProcessAffinityMask)},
        {"CreateHardLinkW", 259, reinterpret_cast<std::uintptr_t>(&tl_CreateHardLinkW)},
        {"K32GetModuleFileNameExW", 260, reinterpret_cast<std::uintptr_t>(&tl_K32GetModuleFileNameExW)},
        {"GetTickCount", 261, reinterpret_cast<std::uintptr_t>(&tl_GetTickCount)},
        {"SetCurrentDirectoryW", 262, reinterpret_cast<std::uintptr_t>(&tl_SetCurrentDirectoryW)},
        {"DeviceIoControl", 263, reinterpret_cast<std::uintptr_t>(&tl_DeviceIoControl)},
        {"FoldStringW", 264, reinterpret_cast<std::uintptr_t>(&tl_FoldStringW)},
        {"SetThreadExecutionState", 265, reinterpret_cast<std::uintptr_t>(&tl_SetThreadExecutionState)},
        {"AllocConsole", 266, reinterpret_cast<std::uintptr_t>(&tl_AllocConsole)},
        {"AttachConsole", 267, reinterpret_cast<std::uintptr_t>(&tl_AttachConsole)},
        {"FreeConsole", 268, reinterpret_cast<std::uintptr_t>(&tl_FreeConsole)},
        {"SystemTimeToTzSpecificLocalTime", 269,
         reinterpret_cast<std::uintptr_t>(&tl_SystemTimeToTzSpecificLocalTime)},
        {"IsDBCSLeadByte", 270, reinterpret_cast<std::uintptr_t>(&tl_IsDBCSLeadByte)},
        {"GetNumberFormatW", 271, reinterpret_cast<std::uintptr_t>(&tl_GetNumberFormatW)},
        {"GetVersion", 272, reinterpret_cast<std::uintptr_t>(&tl_GetVersion)},
        {"GetLargePageMinimum", 273, reinterpret_cast<std::uintptr_t>(&tl_GetLargePageMinimum)},
        {"SetFileApisToOEM", 274, reinterpret_cast<std::uintptr_t>(&tl_SetFileApisToOEM)},
        {"SetConsoleCtrlHandler", 275, reinterpret_cast<std::uintptr_t>(&tl_SetConsoleCtrlHandler)},
        {"GetProcessTimes", 276, reinterpret_cast<std::uintptr_t>(&tl_GetProcessTimes)},
        {"SetProcessAffinityMask", 277, reinterpret_cast<std::uintptr_t>(&tl_SetProcessAffinityMask)},
        {"SetThreadAffinityMask", 278, reinterpret_cast<std::uintptr_t>(&tl_SetThreadAffinityMask)},
        {"ResumeThread", 279, reinterpret_cast<std::uintptr_t>(&tl_ResumeThread)},
        {"OpenEventW", 280, reinterpret_cast<std::uintptr_t>(&tl_OpenEventW)},
        {"OpenFileMappingW", 281, reinterpret_cast<std::uintptr_t>(&tl_OpenFileMappingW)},
        {"FileTimeToDosDateTime", 282, reinterpret_cast<std::uintptr_t>(&tl_FileTimeToDosDateTime)},
        {"CompareFileTime", 283, reinterpret_cast<std::uintptr_t>(&tl_CompareFileTime)},
        {"GetDiskFreeSpaceW", 284, reinterpret_cast<std::uintptr_t>(&tl_GetDiskFreeSpaceW)},
        {"FindFirstStreamW", 285, reinterpret_cast<std::uintptr_t>(&tl_FindFirstStreamW)},
        {"FindNextStreamW", 286, reinterpret_cast<std::uintptr_t>(&tl_FindNextStreamW)},
        {"GetLogicalDriveStringsW", 287, reinterpret_cast<std::uintptr_t>(&tl_GetLogicalDriveStringsW)},
        {"SetNamedPipeHandleState", 288, reinterpret_cast<std::uintptr_t>(&tl_SetNamedPipeHandleState)},
        {"TransactNamedPipe", 289, reinterpret_cast<std::uintptr_t>(&tl_TransactNamedPipe)},
        {"WaitNamedPipeW", 290, reinterpret_cast<std::uintptr_t>(&tl_WaitNamedPipeW)},
        {"PeekNamedPipe", 291, reinterpret_cast<std::uintptr_t>(&tl_PeekNamedPipe)},
        {"WaitForSingleObjectEx", 292, reinterpret_cast<std::uintptr_t>(&tl_WaitForSingleObjectEx)},
        {"GetExitCodeThread", 293, reinterpret_cast<std::uintptr_t>(&tl_GetExitCodeThread)},
        {"TryAcquireSRWLockExclusive", 294, reinterpret_cast<std::uintptr_t>(&tl_TryAcquireSRWLockExclusive)},
        {"FreeLibraryAndExitThread", 295, reinterpret_cast<std::uintptr_t>(&tl_FreeLibraryAndExitThread)},
        {"SetThreadLocale", 296, reinterpret_cast<std::uintptr_t>(&tl_SetThreadLocale)},
        {"SetThreadUILanguage", 297, reinterpret_cast<std::uintptr_t>(&tl_SetThreadUILanguage)},
        {"GetUserDefaultUILanguage", 298, reinterpret_cast<std::uintptr_t>(&tl_GetUserDefaultUILanguage)},
        {"GetLogicalDrives", 299, reinterpret_cast<std::uintptr_t>(&tl_GetLogicalDrives)},
        {"GetPhysicallyInstalledSystemMemory", 300,
         reinterpret_cast<std::uintptr_t>(&tl_GetPhysicallyInstalledSystemMemory)},
        {"GetVolumePathNameA", 301, reinterpret_cast<std::uintptr_t>(&tl_GetVolumePathNameA)},
        {"TzSpecificLocalTimeToSystemTime", 302,
         reinterpret_cast<std::uintptr_t>(&tl_TzSpecificLocalTimeToSystemTime)},
        {"UnregisterWaitEx", 303, reinterpret_cast<std::uintptr_t>(&tl_UnregisterWaitEx)},
        {"RegisterWaitForSingleObject", 304,
         reinterpret_cast<std::uintptr_t>(&tl_RegisterWaitForSingleObject)},
        {"SetSearchPathMode", 305, reinterpret_cast<std::uintptr_t>(&tl_SetSearchPathMode)},
        {"InterlockedPushEntrySList", 306,
         reinterpret_cast<std::uintptr_t>(&tl_InterlockedPushEntrySList)},
        {"CopyFileExW", 307, reinterpret_cast<std::uintptr_t>(&tl_CopyFileExW)},
        {"MoveFileWithProgressW", 308, reinterpret_cast<std::uintptr_t>(&tl_MoveFileWithProgressW)},
        {"GetCompressedFileSizeW", 309, reinterpret_cast<std::uintptr_t>(&tl_GetCompressedFileSizeW)},
        {"FindFirstChangeNotificationW", 310,
         reinterpret_cast<std::uintptr_t>(&tl_FindFirstChangeNotificationW)},
        {"FindNextChangeNotification", 311,
         reinterpret_cast<std::uintptr_t>(&tl_FindNextChangeNotification)},
        {"FindCloseChangeNotification", 312,
         reinterpret_cast<std::uintptr_t>(&tl_FindCloseChangeNotification)},
        {"GetSystemDefaultLangID", 313, reinterpret_cast<std::uintptr_t>(&tl_GetSystemDefaultLangID)},
        {"GetUserDefaultLangID", 314, reinterpret_cast<std::uintptr_t>(&tl_GetUserDefaultLangID)},
        {"GetWindowsDirectoryW", 315, reinterpret_cast<std::uintptr_t>(&tl_GetWindowsDirectoryW)},
        {"GlobalSize", 316, reinterpret_cast<std::uintptr_t>(&tl_GlobalSize)},
        {"SetPriorityClass", 317, reinterpret_cast<std::uintptr_t>(&tl_SetPriorityClass)},
        {"lstrlenW", 318, reinterpret_cast<std::uintptr_t>(&tl_lstrlenW)},
        {"K32GetProcessMemoryInfo", 319, reinterpret_cast<std::uintptr_t>(&tl_K32GetProcessMemoryInfo)},
        {"K32GetProcessImageFileNameA", 320, reinterpret_cast<std::uintptr_t>(&tl_K32GetProcessImageFileNameA)},
        {"Process32First", 321, reinterpret_cast<std::uintptr_t>(&tl_Process32First)},
        {"Process32Next", 322, reinterpret_cast<std::uintptr_t>(&tl_Process32Next)},
        {"DuplicateHandle", 323, reinterpret_cast<std::uintptr_t>(&tl_DuplicateHandle)},
        {"LockFile", 324, reinterpret_cast<std::uintptr_t>(&tl_LockFile)},
        {"LockFileEx", 325, reinterpret_cast<std::uintptr_t>(&tl_LockFileEx)},
        {"UnlockFile", 326, reinterpret_cast<std::uintptr_t>(&tl_UnlockFile)},
        {"UnlockFileEx", 327, reinterpret_cast<std::uintptr_t>(&tl_UnlockFileEx)},
        {"GetDiskFreeSpaceA", 328, reinterpret_cast<std::uintptr_t>(&tl_GetDiskFreeSpaceA)},
        {"GetTempPathA", 329, reinterpret_cast<std::uintptr_t>(&tl_GetTempPathA)},
        {"MoveFileExA", 330, reinterpret_cast<std::uintptr_t>(&tl_MoveFileExA)},
        {"SleepEx", 331, reinterpret_cast<std::uintptr_t>(&tl_SleepEx)},
        {"WaitForMultipleObjectsEx", 332, reinterpret_cast<std::uintptr_t>(&tl_WaitForMultipleObjectsEx)},
        {"TryEnterCriticalSection", 333, reinterpret_cast<std::uintptr_t>(&tl_TryEnterCriticalSection)},
        {"InitializeConditionVariable", 334, reinterpret_cast<std::uintptr_t>(&tl_InitializeConditionVariable)},
        {"SleepConditionVariableCS", 335, reinterpret_cast<std::uintptr_t>(&tl_SleepConditionVariableCS)},
        {"FindResourceExW", 336, reinterpret_cast<std::uintptr_t>(&tl_FindResourceExW)},
        {"CompareStringEx", 337, reinterpret_cast<std::uintptr_t>(&tl_CompareStringEx)},
        {"CreateFile2", 338, reinterpret_cast<std::uintptr_t>(&tl_CreateFile2)},
        {"GetCurrentProcessorNumber", 339, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentProcessorNumber)},
        {"InitializeProcThreadAttributeList", 340, reinterpret_cast<std::uintptr_t>(&tl_InitializeProcThreadAttributeList)},
        {"UpdateProcThreadAttribute", 341, reinterpret_cast<std::uintptr_t>(&tl_UpdateProcThreadAttribute)},
        {"GetSystemDirectoryA", 342, reinterpret_cast<std::uintptr_t>(&tl_GetSystemDirectoryA)},
        {"ReadConsoleA", 343, reinterpret_cast<std::uintptr_t>(&tl_ReadConsoleA)},
        {"CreateWaitableTimerA", 344, reinterpret_cast<std::uintptr_t>(&tl_CreateWaitableTimerA)},
        {"CreateWaitableTimerW", 345, reinterpret_cast<std::uintptr_t>(&tl_CreateWaitableTimerW)},
        {"SetWaitableTimer", 346, reinterpret_cast<std::uintptr_t>(&tl_SetWaitableTimer)},
        {"CancelWaitableTimer", 347, reinterpret_cast<std::uintptr_t>(&tl_CancelWaitableTimer)},
        {"GetLogicalProcessorInformation", 348, reinterpret_cast<std::uintptr_t>(&tl_GetLogicalProcessorInformation)},
        {"GetVolumePathNameW", 349, reinterpret_cast<std::uintptr_t>(&tl_GetVolumePathNameW)},
        {"SetThreadDescription", 350, reinterpret_cast<std::uintptr_t>(&tl_SetThreadDescription)},
        {"GetCurrentThread", 351, reinterpret_cast<std::uintptr_t>(&tl_GetCurrentThread)},
        {"CreateSemaphoreExW", 352, reinterpret_cast<std::uintptr_t>(&tl_CreateSemaphoreExW)},
        {"OpenSemaphoreW", 353, reinterpret_cast<std::uintptr_t>(&tl_OpenSemaphoreW)},
        {"CreateMutexExW", 354, reinterpret_cast<std::uintptr_t>(&tl_CreateMutexExW)},
        {"DebugBreak", 355, reinterpret_cast<std::uintptr_t>(&tl_DebugBreak)},
        {"InitOnceBeginInitialize", 356, reinterpret_cast<std::uintptr_t>(&tl_InitOnceBeginInitialize)},
        {"InitOnceComplete", 357, reinterpret_cast<std::uintptr_t>(&tl_InitOnceComplete)},
        {"SwitchToThread", 358, reinterpret_cast<std::uintptr_t>(&tl_SwitchToThread)},
        {"GetSystemFirmwareTable", 359, reinterpret_cast<std::uintptr_t>(&tl_GetSystemFirmwareTable)},
        {"__C_specific_handler", 360, reinterpret_cast<std::uintptr_t>(&tl___C_specific_handler)},
        {"Beep", 361, reinterpret_cast<std::uintptr_t>(&tl_Beep)},
        {"ClearCommBreak", 362, reinterpret_cast<std::uintptr_t>(&tl_ClearCommBreak)},
        {"ConnectNamedPipe", 363, reinterpret_cast<std::uintptr_t>(&tl_ConnectNamedPipe)},
        {"CreateNamedPipeA", 364, reinterpret_cast<std::uintptr_t>(&tl_CreateNamedPipeA)},
        {"CreatePipe", 365, reinterpret_cast<std::uintptr_t>(&tl_CreatePipe)},
        {"FindResourceA", 366, reinterpret_cast<std::uintptr_t>(&tl_FindResourceA)},
        {"GetCommState", 367, reinterpret_cast<std::uintptr_t>(&tl_GetCommState)},
        {"GetLocaleInfoA", 368, reinterpret_cast<std::uintptr_t>(&tl_GetLocaleInfoA)},
        {"GetOverlappedResult", 369, reinterpret_cast<std::uintptr_t>(&tl_GetOverlappedResult)},
        {"GetThreadTimes", 370, reinterpret_cast<std::uintptr_t>(&tl_GetThreadTimes)},
        {"GetWindowsDirectoryA", 371, reinterpret_cast<std::uintptr_t>(&tl_GetWindowsDirectoryA)},
        {"GlobalMemoryStatus", 372, reinterpret_cast<std::uintptr_t>(&tl_GlobalMemoryStatus)},
        {"LocalFileTimeToFileTime", 373, reinterpret_cast<std::uintptr_t>(&tl_LocalFileTimeToFileTime)},
        {"SetCommBreak", 374, reinterpret_cast<std::uintptr_t>(&tl_SetCommBreak)},
        {"SetCommState", 375, reinterpret_cast<std::uintptr_t>(&tl_SetCommState)},
        {"SetCommTimeouts", 376, reinterpret_cast<std::uintptr_t>(&tl_SetCommTimeouts)},
        {"SetCurrentDirectoryA", 377, reinterpret_cast<std::uintptr_t>(&tl_SetCurrentDirectoryA)},
        {"SetHandleInformation", 378, reinterpret_cast<std::uintptr_t>(&tl_SetHandleInformation)},
        {"WaitNamedPipeA", 379, reinterpret_cast<std::uintptr_t>(&tl_WaitNamedPipeA)},
        {"CreateProcessA", 380, reinterpret_cast<std::uintptr_t>(&tl_CreateProcessA)},
        {"GetTimeFormatEx", 381, reinterpret_cast<std::uintptr_t>(&tl_GetTimeFormatEx)},
        {"GetDateFormatEx", 382, reinterpret_cast<std::uintptr_t>(&tl_GetDateFormatEx)},
        {"lstrcpynW", 383, reinterpret_cast<std::uintptr_t>(&tl_lstrcpynW)},
        {"GetApplicationRestartSettings", 384, reinterpret_cast<std::uintptr_t>(&tl_GetApplicationRestartSettings)},
        {"UnregisterApplicationRestart", 385, reinterpret_cast<std::uintptr_t>(&tl_UnregisterApplicationRestart)},
        {"lstrcmpiA", 386, reinterpret_cast<std::uintptr_t>(&tl_lstrcmpiA)},
        {"RegisterApplicationRestart", 387, reinterpret_cast<std::uintptr_t>(&tl_RegisterApplicationRestart)},
        {"lstrcpynA", 388, reinterpret_cast<std::uintptr_t>(&tl_lstrcpynA)},
        {"CancelIo", 389, reinterpret_cast<std::uintptr_t>(&tl_CancelIo)},
        {"ReadDirectoryChangesW", 390, reinterpret_cast<std::uintptr_t>(&tl_ReadDirectoryChangesW)},
        {"GetStringTypeExW", 391, reinterpret_cast<std::uintptr_t>(&tl_GetStringTypeExW)},
        {"LCMapStringA", 392, reinterpret_cast<std::uintptr_t>(&tl_LCMapStringA)},
        {"GetStringTypeExA", 393, reinterpret_cast<std::uintptr_t>(&tl_GetStringTypeExA)},
        {"FreeLibraryWhenCallbackReturns", 394, reinterpret_cast<std::uintptr_t>(&tl_FreeLibraryWhenCallbackReturns)},
        {"lstrcpyW", 395, reinterpret_cast<std::uintptr_t>(&tl_lstrcpyW)},
        {"ReplaceFileW", 396, reinterpret_cast<std::uintptr_t>(&tl_ReplaceFileW)},
        {"QueueUserAPC", 397, reinterpret_cast<std::uintptr_t>(&tl_QueueUserAPC)},
        {"lstrcmpW", 398, reinterpret_cast<std::uintptr_t>(&tl_lstrcmpW)},
        {"lstrcmpiW", 399, reinterpret_cast<std::uintptr_t>(&tl_lstrcmpiW)},
        {"DosDateTimeToFileTime", 400, reinterpret_cast<std::uintptr_t>(&tl_DosDateTimeToFileTime)},
        {"CreateRemoteThread", 401, reinterpret_cast<std::uintptr_t>(&tl_CreateRemoteThread), ExportSupport::Stub},
        {"VirtualAllocEx", 402, reinterpret_cast<std::uintptr_t>(&tl_VirtualAllocEx)},
        {"VirtualFreeEx", 403, reinterpret_cast<std::uintptr_t>(&tl_VirtualFreeEx)},
        {"WriteProcessMemory", 404, reinterpret_cast<std::uintptr_t>(&tl_WriteProcessMemory), ExportSupport::Stub},
        {"OpenFile", 405, reinterpret_cast<std::uintptr_t>(&tl_OpenFile)},
        {"OpenEventA", 406, reinterpret_cast<std::uintptr_t>(&tl_OpenEventA)},
        {"OpenFileMappingA", 407, reinterpret_cast<std::uintptr_t>(&tl_OpenFileMappingA)},
        {"_lclose", 408, reinterpret_cast<std::uintptr_t>(&tl__lclose)},
        {"FlushInstructionCache", 409, reinterpret_cast<std::uintptr_t>(&tl_FlushInstructionCache)},
        {"SetThreadContext", 410, reinterpret_cast<std::uintptr_t>(&tl_SetThreadContext)},
        {"GetThreadContext", 411, reinterpret_cast<std::uintptr_t>(&tl_GetThreadContext)},
        {"SuspendThread", 412, reinterpret_cast<std::uintptr_t>(&tl_SuspendThread)},
        {"VirtualProtectEx", 413, reinterpret_cast<std::uintptr_t>(&tl_VirtualProtectEx)},
        {"lstrcmpA", 414, reinterpret_cast<std::uintptr_t>(&tl_lstrcmpA)},
        {"IsThreadAFiber", 415, reinterpret_cast<std::uintptr_t>(&tl_IsThreadAFiber)},
        {"InterlockedFlushSList", 416, reinterpret_cast<std::uintptr_t>(&tl_InterlockedFlushSList)},
        {"lstrcatW", 417, reinterpret_cast<std::uintptr_t>(&tl_lstrcatW)},
    };
    static const InternalModule kKernel32Module{"KERNEL32.dll", kKernel32Exports};
    register_module(kKernel32Module);
}

}  // namespace tradutorlinux::loader
